// Voci per il DB cruciverba - versione piu difficile e ampliata.
// Definizioni rese meno immediate: piu seconde accezioni, indizi laterali, cultura generale e ambiguita controllata.
// Risposte senza accenti; definizioni in stile ASCII per compatibilita.
const NEW = [];

// ===================== 2 LETTERE (96 voci) =====================
NEW.push(["AL", "Tra Tanaro e Bormida, sulle targhe"],["AN", "Ancona ridotta a targa"],["AP", "Ascoli Piceno in due caselle automobilistiche"],["AQ", "L'Aquila quando si fa sigla"]);
NEW.push(["AT", "Asti, quando occupa due caselle"],["AU", "L'oro nelle tavole, non in gioielleria"],["AV", "Irpinia sulle targhe"],["BA", "Il capoluogo pugliese in formato minimo"]);
NEW.push(["BI", "Biella in formato automobilistico"],["BN", "Benevento in due lettere"],["BO", "Coppia di lettere felsinee"],["BR", "Citta brindisina che sembra gia un brindisi"]);
NEW.push(["CA", "La citta del Casteddu sulle targhe"],["CB", "Campobasso sul paraurti"],["CD", "Un disco ormai un po' d'epoca"],["CE", "Caserta senza reggia, sulle targhe"]);
NEW.push(["CH", "Chieti in due lettere da auto"],["CL", "Caltanissetta accorciata al massimo"],["CO", "Lario in sigla automobilistica"],["CR", "Cremona, quando diventa sigla"]);
NEW.push(["CS", "Cosenza in targa"],["CT", "Etna e Catania in due lettere"],["CU", "Il rame senza alchimie"],["CZ", "Catanzaro in formato minimo"]);
NEW.push(["EN", "Enna sulle auto dell'entroterra siciliano"],["FA", "Nota che non ha bisogno di diesis per seguire il mi"],["FC", "Forli-Cesena in sigla"],["FE", "Il ferro quando parla il chimico"]);
NEW.push(["FG", "Foggia sulle targhe"],["FI", "Dante e l'Arno in due lettere"],["FR", "Frosinone in sigla automobilistica"],["GE", "La Superba, ridotta a targa"]);
NEW.push(["GO", "Antico gioco con pietre bianche e nere"],["IM", "Imperia senza riviera, in targa"],["IO", "Il soggetto piu ingombrante, in due lettere"],["IS", "Isernia per automobilisti"]);
NEW.push(["KR", "Crotone con sigla moderna"],["LA", "Nota o articolo: due caselle ambigue"],["LC", "Lecco sulle targhe del Lario"],["LE", "Salento in due lettere"]);
NEW.push(["LI", "Livorno in forma minima"],["LT", "Latina sulle auto"],["LU", "Lucca entro due caselle"],["MC", "Macerata in sigla"]);
NEW.push(["ME", "Messina sul paraurti"],["MI", "La Madonnina da paraurti"],["MN", "Mantova in sigla d'auto"],["MO", "Modena in formato targa"]);
NEW.push(["MS", "Massa-Carrara sulle targhe"],["MT", "Matera ridotta a due lettere"],["NA", "Partenope in sigla"],["NE", "Particella che puo valere di cio"]);
NEW.push(["NO", "Novara, ma sembra una negazione"],["NU", "Nuoro sulle targhe sarde"],["OR", "Oristano in due lettere"],["PA", "Due lettere panormite"]);
NEW.push(["PC", "Piacenza come una sigla informatica"],["PD", "La citta del Santo in sigla"],["PE", "Pescara senza mare, in targa"],["PG", "Perugia sulle targhe umbre"]);
NEW.push(["PI", "La citta della torre quando diventa targa"],["PN", "Pordenone in breve automobilistico"],["PO", "Fiume breve di nome, lungo di corso"],["PR", "Parma da paraurti"]);
NEW.push(["PT", "Pistoia in sigla"],["PV", "Pavia sulle targhe"],["PZ", "Potenza in due lettere"],["RA", "Ravenna in sigla, ma pare un dio egizio"]);
NEW.push(["RC", "Reggio Calabria in targa"],["RE", "Reggio Emilia e una nota musicale"],["RI", "Rieti in due caselle"],["RM", "La Roma che entrava nelle vecchie sigle automobilistiche"]);
NEW.push(["RN", "Rimini sulle targhe romagnole"],["RO", "Rovigo in sigla"],["SA", "Salerno in targa"],["SI", "Nota e assenso: due caselle bastano"]);
NEW.push(["SO", "Valtellina sulle automobili"],["SP", "La Spezia in formato breve"],["SR", "Siracusa sulle targhe"],["SU", "Direzione da ascensore"]);
NEW.push(["SV", "Savona da paraurti"],["TA", "Taranto in due lettere"],["TE", "Teramo in sigla"],["TO", "Due lettere sabaude da paraurti"]);
NEW.push(["TS", "Bora e porto in due lettere"],["TU", "Un interlocutore senza cerimonie"],["TV", "Schermo domestico in due lettere"],["UD", "Udine in targa friulana"]);
NEW.push(["UE", "Ventisette in due lettere"],["VA", "Varese, ma anche voce del verbo andare"],["VB", "Verbano-Cusio-Ossola in sigla"],["VC", "Vercelli in targa"]);
NEW.push(["VE", "Venezia senza gondole, in sigla"],["VI", "Vicenza in due caselle"],["VR", "Arena ridotta a due lettere"],["VT", "Viterbo sulle targhe laziali"]);

// ===================== 3 LETTERE (176 voci) =====================
NEW.push(["ABI", "Codice bancario italiano in tre lettere"],["ACE", "Servizio che non si ribatte"],["ADA", "Nome breve e linguaggio di programmazione"],["ADE", "Regno oscuro dei Greci"]);
NEW.push(["AGO", "Entra dove il filo lo segue"],["AIA", "Cortile rustico da trebbiatura"],["ALA", "Fianco che puo volare"],["ALE", "Fa allegria solo se le manca il resto"]);
NEW.push(["ALI", "Le cercano Icaro e ogni velivolo"],["AMA", "Vuole bene in terza persona"],["AMO", "Inganna chi abbocca"],["APO", "Prima parte di apostrofo"]);
NEW.push(["ARA", "Altare antico o pappagallo colorato"],["ARE", "Misura agraria di cento metri quadrati"],["ASA", "Sigla dell'aspirina in chimica farmaceutica"],["ASE", "Sterile se gli metti davanti la a"]);
NEW.push(["AVA", "Nome da diva Gardner"],["AVE", "Saluto romano prima d'essere preghiera"],["AVI", "Formato video di vecchia fortuna"],["AVO", "Un nonno risalito di qualche generazione"]);
NEW.push(["BAR", "Ha banco, ma non sempre carte"],["BEA", "Rende felice in forma letteraria"],["BIO", "Prefisso che promette naturalezza"],["BIS", "Si chiede quando l'applauso non basta"]);
NEW.push(["BOA", "Anello galleggiante o serpente da leggenda"],["BOB", "Scivola sul ghiaccio in squadra"],["BOH", "Risposta di chi non sa"],["BUA", "Piccolo male detto ai bambini"]);
NEW.push(["BUE", "Lo aggioga il contadino d'altri tempi"],["CEO", "Capo aziendale in sigla anglosassone"],["CIA", "A Langley la scrivono cosi"],["CIS", "Diesis al contrario, per il musicista"]);
NEW.push(["COL", "Preposizione fusa con l'articolo"],["CON", "Preposizione di compagnia o mezzo"],["CUI", "Pronome da complemento"],["DAI", "Incitamento da panchina o da tavolo"]);
NEW.push(["DAL", "Da piu articolo in una sillaba"],["DEA", "Una che sull'Olimpo non invecchia"],["DEI", "Plurale da Olimpo"],["DEL", "Articolo partitivo o preposizione articolata"]);
NEW.push(["DIO", "Nome altissimo in tre caselle"],["DOC", "Garantito, o medico nei film americani"],["DON", "Titolo ecclesiastico o boss da cinema"],["DOP", "Marchio alimentare protetto"]);
NEW.push(["DOS", "Vecchio sistema prima delle finestre"],["DUE", "Basta per fare coppia, non folla"],["DUO", "Coppia che suona"],["ECO", "Risposta che non pensa"]);
NEW.push(["EGO", "L'io quando si mette in analisi"],["EMO", "Sangue in forma di prefisso"],["EMU", "Corre in Australia senza prendere il volo"],["ENI", "Sigla energetica con sei zampe nel marchio"]);
NEW.push(["ERA", "Tempo lungo o voce del verbo essere"],["ERO", "Fui, in tre lettere"],["ESA", "Spazio europeo in tre lettere"],["ETA", "Si conta senza fermarla"]);
NEW.push(["FAI", "Agisci o sigla dei beni culturali"],["FAN", "Vive di idoli e autografi"],["FAX", "Documento arrivato con un fischio d'epoca"],["FBI", "Indaga a stelle e strisce"]);
NEW.push(["FEZ", "Copricapo che porta una nappa"],["FIE", "Debole, se la completi"],["FIO", "Si paga per espiare"],["GAS", "Puo uscire da un fornello o da una risata"]);
NEW.push(["GEL", "Tiene in riga i capelli"],["GIA", "Avverbio che arriva prima del previsto"],["GIN", "Alcolico caro al tonic"],["GOL", "Rete senza inglesismi"]);
NEW.push(["GRU", "Uccello o macchina da cantiere"],["ICO", "In icona, senza inizio e fine"],["IDE", "Apre l'ideale senza raggiungerlo"],["IRA", "Collera breve e latina"]);
NEW.push(["IRI", "Vecchia sigla dell'industria pubblica italiana"],["ISO", "Standard internazionale in tre lettere"],["IVA", "La percentuale che gonfia lo scontrino"],["KIT", "Occorre prima di montare"]);
NEW.push(["LAO", "Lingua e popolo del Sud-est asiatico"],["LEI", "Distanza di cortesia in tre lettere"],["LEO", "Leone accorciato a nome"],["LIA", "Nome breve da romanzo"]);
NEW.push(["LOG", "Registro tecnico o tronco inglese"],["LUI", "Maschile quando non si nomina il nome"],["LUX", "Unita di illuminamento"],["MAI", "Tempo negato"]);
NEW.push(["MEA", "Confessione latina prima di culpa"],["MIA", "Possessivo femminile in tre caselle"],["MIO", "Possessivo geloso e breve"],["NEA", "Apre il napoletano senza Napoli"]);
NEW.push(["NEL", "Dentro, con articolo incorporato"],["NEO", "Macchia, difetto o prefisso del nuovo"],["NET", "Rete in inglese, ma non sempre web"],["NOI", "L'io quando si allarga"]);
NEW.push(["NON", "La sillaba che rovescia il senso"],["OCA", "Animale proverbiale per sciocchezza"],["ODE", "Versi solenni, spesso poco quotidiani"],["OHM", "Resistenza scritta senza opporsi"]);
NEW.push(["OLE", "Esclamazione da arena spagnola"],["OMO", "Uomo in forma antica o prefisso uguale"],["ONU", "Assemblea mondiale in tre lettere"],["OPA", "Offerta pubblica in Borsa"]);
NEW.push(["OPS", "Scusa in tre lettere"],["ORA", "Adesso o sessanta minuti"],["ORE", "Pluralizza il tempo dell'orologio"],["ORO", "Metallo che fa gola e medaglie"]);
NEW.push(["OSA", "Invito proverbiale a rischiare"],["OVA", "Uova ittiche, piu da scienza che da cucina"],["PAN", "Tutto, come prefisso greco"],["PER", "Si mette fra fattori e prodotti"]);
NEW.push(["PIA", "Devota al femminile"],["PIN", "Codice che apre senza chiave"],["PIO", "Devoto, anche quando diventa nome"],["PIU", "Segno che aggiunge senza parlare"]);
NEW.push(["POI", "Tempo che rinvia"],["PRO", "A favore, in tre lettere"],["QUA", "Qui, ma con altra vocale"],["RAI", "Tre lettere davanti al canone"]);
NEW.push(["RAP", "Rime su base battente"],["REA", "Colpevole declinata al femminile"],["REM", "Fase del sonno che muove gli occhi"],["REO", "Uno che il giudice non assolve"]);
NEW.push(["RES", "La cosa dei giuristi latini"],["RIO", "Corso d'acqua o citta brasiliana abbreviata"],["ROC", "Uccello favoloso da Mille e una notte"],["RUM", "Caraibico nel bicchiere"]);
NEW.push(["SAN", "Titolo davanti a molti nomi sacri"],["SCI", "Ha lamine e discese"],["SEI", "Numero o verbo essere"],["SEN", "Titolo da parlamento abbreviato"]);
NEW.push(["SER", "Titolo antico spagnolo o inizio di serpente"],["SET", "Un parziale che non e solo nel tennis"],["SIA", "Congiunzione che raddoppia spesso"],["SIR", "Titolo britannico in tre lettere"]);
NEW.push(["SOL", "Nota che illumina anche senza sole"],["SOS", "Richiesta d'aiuto senza parole"],["STA", "Rimane o si trova"],["STO", "Questo, in forma tronca"]);
NEW.push(["SUD", "Il punto che sui mappamondi scende"],["SUE", "Possessivo di terza al femminile plurale"],["SUI", "Su piu articolo plurale"],["SUL", "Sopra, con articolo incorporato"]);
NEW.push(["TAC", "Scatto di serratura o esame per immagini"],["TAN", "Tangente abbreviata dai matematici"],["TAO", "Via orientale piu che strada"],["TAR", "Tribunale amministrativo in tre lettere"]);
NEW.push(["TEA", "Rosa da salotto inglese"],["TEE", "Supporto minuscolo del golfista"],["TEL", "Telefono in rubrica abbreviata"],["TEO", "In testa a un teorema"]);
NEW.push(["TIC", "Scatto nervoso e ripetuto"],["TIR", "Bestione autostradale"],["TOP", "Il massimo, in inglese entrato nell'uso"],["TOT", "Quantita imprecisa ma fissata"]);
NEW.push(["TRA", "Sta in mezzo anche quando e preposizione"],["TRE", "Il primo dispari dopo l'unita composta"],["UDO", "Sento in un verbo poco quotidiano"],["UFO", "Appare nei cieli di chi non sa identificarlo"]);
NEW.push(["UNO", "Numero, carta o pronome impersonale"],["URL", "Indirizzo che non arriva per posta"],["USO", "Consuetudine che diventa diritto"],["UTE", "Veicolo utilitario australiano"]);
NEW.push(["UVA", "Prima del vino, se non resta frutto"],["VAI", "Invito a muoversi senza indugio"],["VAL", "Vale, se gli togli l'ultima lettera"],["VAN", "Mezzo chiuso, spesso da trasloco"]);
NEW.push(["VIA", "Strada o ordine di partenza"],["VIE", "Strade al plurale, ma anche vie di fuga"],["VIP", "Persona importante per acronimo"],["VOL", "Volume abbreviato in biblioteca"]);
NEW.push(["WEB", "Rete che non pesca"],["WOK", "Padella orientale dal fondo concavo"],["YEN", "Denaro di Tokyo"],["YES", "Assenso inglese in tre caselle"]);
NEW.push(["ZAR", "Autocrate in tre lettere"],["ZEN", "Silenzio giapponese da meditazione"],["ZIA", "Parente che non fa da genitore"],["ZOO", "Raccolta di fauna dietro recinti"]);

// ===================== 4 LETTERE (413 voci) =====================
NEW.push(["ADDA", "Fiume lombardo caro ai cruciverba"],["AGIO", "Comodita o vantaggio di cambio"],["AGRO", "Aspro e campagna romana"],["AIDA", "Eroina verdiana sulle rive del Nilo"]);
NEW.push(["ALBA", "Il momento in cui il buio comincia a cedere"],["ALCE", "Cervide che porta un palco senza teatro"],["ALFA", "Prima lettera greca e marchio d'auto"],["ALGA", "Verde sommerso che non e insalata"]);
NEW.push(["ALPE", "Rilievo alpino in forma singolare"],["AMBA", "Numero secco al lotto"],["AMBO", "Coppia vincente sulla ruota"],["AMEN", "Chiusura liturgica in quattro lettere"]);
NEW.push(["ANCA", "Giuntura laterale da ballerino e ortopedico"],["ANNO", "Un giro completo del calendario"],["ANSA", "Curva di fiume o agenzia stampa"],["ANTE", "Battenti che non battono"]);
NEW.push(["APSE", "Spazio sacro dietro l'altare"],["ARCO", "Tende la corda o unisce due pilastri"],["AREA", "Superficie da misurare o zona"],["ARGO", "Cane fedele e nave mitica"]);
NEW.push(["ARIA", "Manca quando si boccheggia"],["ARMA", "Ha bisogno d'una mano e d'un bersaglio"],["ARNO", "Attraversa Firenze senza entrar nei musei"],["ARSO", "Ridotto dal calore a memoria di fuoco"]);
NEW.push(["ARTE", "Fa mestiere del bello e del difficile"],["ASIA", "Oriente vastissimo su carte scolastiche"],["ASSO", "Carta che puo valere uno o piu del re"],["ATTO", "Ha scene, ma anche valore notarile"]);
NEW.push(["AURA", "Atmosfera che circonda senza toccare"],["AUTO", "Veicolo che nel prefisso fa da se"],["AZIO", "Sconfitta navale di Antonio e Cleopatra"],["BACO", "Filatore prima di essere farfalla"]);
NEW.push(["BAIA", "Riparo marino che invita all'ancora"],["BAIO", "Cavallo di mantello rossiccio"],["BALI", "Isola indonesiana da templi e surf"],["BARA", "Ultimo contenitore di chi non viaggia piu"]);
NEW.push(["BASE", "Sostegno o punto di partenza"],["BENE", "Lo si oppone al male e lo si vuole"],["BETA", "Seconda lettera greca e versione provvisoria"],["BICE", "Nome femminile che sa di romanzo ottocentesco"]);
NEW.push(["BILE", "Amarezza organica e figurata"],["BIRO", "Penna che porta il nome dell'inventore"],["BOIA", "Faceva lavoro di morte per legge"],["BORA", "Soffia triestina e tagliente"]);
NEW.push(["BRIO", "Vivacita che frizza"],["BUCA", "La cerca il golfista, la teme l'automobilista"],["BUCO", "Vuoto concreto o debito informale"],["BUIO", "Regno dove gli occhi lavorano male"]);
NEW.push(["CACO", "Frutto arancione, meno elegante di kaki"],["CALO", "Ribasso che alleggerisce numeri o peso"],["CANE", "Abbaia, ma sta anche nelle armi antiche"],["CANI", "Pluralita che abbaia"]);
NEW.push(["CAPI", "Comandano o si indossano"],["CAPO", "Estremita, promontorio o superiore"],["CARI", "Amati o costosi"],["CARO", "Amato oppure poco conveniente"]);
NEW.push(["CASA", "Puo essere editrice, regnante o di abitazione"],["CASO", "Lo invoca chi non trova una causa"],["CAVE", "Miniere a cielo aperto"],["CAVI", "Fili con anima di metallo"]);
NEW.push(["CAVO", "Vuoto, oppure filo pieno di corrente"],["CECI", "Legumi che diventano purea mediorientale"],["CECO", "Slavo di Praga, non cieco"],["CENA", "Pasto che arriva quando il giorno finisce"]);
NEW.push(["CERA", "Dalle api ai pavimenti lucidi"],["CIAO", "Saluto buono all'arrivo e alla partenza"],["CIBO", "La materia prima del convivio"],["CILE", "Lungo Paese sul Pacifico"]);
NEW.push(["CIMA", "Punto alto, in montagna o in marina"],["CINA", "Impero di mezzo nei libri di storia"],["CITO", "Richiamo testualmente o convoco in giudizio"],["COLA", "Lascia passare il liquido, non il solido"]);
NEW.push(["CONO", "Solido del gelataio e del geometra"],["CORO", "Molte voci che fanno una sola parte"],["COSA", "Nome rifugio quando manca il nome"],["COVO", "Rifugio piu da banditi che da eremiti"]);
NEW.push(["CUBO", "Ha sei facce e poca fantasia"],["CURE", "Attenzioni mediche e premurose"],["DADI", "Cubetti da brodo o da gioco"],["DADO", "Si getta per affidarsi alla sorte"]);
NEW.push(["DALI", "Baffi surrealisti in quattro lettere"],["DAMA", "Gioco a pedine o signora d'altri tempi"],["DARE", "Verbo generoso o commerciale"],["DATA", "Numeri che collocano un giorno"]);
NEW.push(["DINO", "Nome proprio e diminutivo da dinosauro"],["DITA", "Finiscono la mano e iniziano le impronte"],["DIVO", "Vive di schermi e ammiratori"],["DODO", "Uccello estinto che non volava lontano"]);
NEW.push(["DOGE", "Serenissimo titolo veneziano"],["DOPO", "Avverbio che prende tempo"],["DOSE", "La misura che puo curare o nuocere"],["DOTE", "Qualita innata o corredo nuziale"]);
NEW.push(["DUCA", "Nobile sotto il principe, sopra il marchese"],["DUNA", "Onda ferma del deserto"],["DURO", "Resiste, o manca di tenerezza"],["EDEN", "Giardino perduto per un frutto"]);
NEW.push(["EIRE", "Irlanda in forma poetica e politica"],["ELBA", "Isola napoleonica del Tirreno"],["ELFO", "Piccolo essere da boschi nordici"],["ELMO", "Copre il capo prima della corona"]);
NEW.push(["EMIR", "Titolo arabo da palazzo"],["ENNA", "Citta alta nel cuore della Sicilia"],["ENTE", "Soggetto giuridico senza corpo"],["ERBA", "La calpestano mucche e calciatori"]);
NEW.push(["ERMO", "Solitario, come il colle leopardiano"],["EROE", "Fa imprese che altri raccontano"],["EROS", "Amore con nome greco"],["ESCA", "Inganno commestibile per pesci"]);
NEW.push(["ESSE", "Lettera sinuosa"],["ETNA", "Fuma sopra la Sicilia orientale"],["EURO", "Moneta comune a molte tasche europee"],["FADO", "Canto portoghese pieno di saudade"]);
NEW.push(["FAMA", "Corre piu dei suoi protagonisti"],["FARE", "Verbo che trasforma intenzioni in atti"],["FARO", "Occhio costiero per chi naviga"],["FASE", "Passaggio di luna o di progetto"]);
NEW.push(["FATA", "Dispensa incanti nelle fiabe"],["FATO", "Destino con tono antico"],["FAVA", "Legume che ha nome anche in proverbi"],["FAVO", "Opera geometrica delle api"]);
NEW.push(["FEBE", "Titano lunare dal nome luminoso"],["FEBO", "Apollo in veste luminosa"],["FEDE", "Si porta all'anulare o nel cuore"],["FETO", "Vita non ancora venuta alla luce"]);
NEW.push(["FICO", "Frutto, albero e complimento colloquiale"],["FIDO", "Nome da cane affidabile"],["FILA", "Coda che non scodinzola"],["FILO", "Unisce stoffe o pensieri sottili"]);
NEW.push(["FINE", "Conclusione, ma anche scopo"],["FOCA", "Nuota nei mari freddi con baffi da circo"],["FOCI", "Sbocchi di fiumi, non bocche qualunque"],["FOGA", "Impeto che dimentica la misura"]);
NEW.push(["FOLK", "Popolare in musica"],["FORO", "Piazza antica, tribunale o buco"],["FOTO", "Memoria fissata dalla luce"],["FRAC", "Abito maschile da cerimonia severa"]);
NEW.push(["FUGA", "Scappa, ma in musica segue regole severe"],["FUMO", "Segnale di fuoco e vizio"],["FUNE", "Corda da pozzo o da acrobata"],["FUSO", "Serve alla filatrice e al fuso orario"]);
NEW.push(["GAIA", "Lieta, ma anche Terra primordiale"],["GALA", "Serata che pretende abiti importanti"],["GARA", "Confronto in cui conta l'arrivo"],["GELO", "Freddo che fa tacere anche il terreno"]);
NEW.push(["GENE", "Unita ereditaria invisibile"],["GIRO", "Viaggio in tondo o corsa rosa"],["GITA", "Viaggio breve, spesso senza valigia grande"],["GOAL", "Rete che non si pesca"]);
NEW.push(["GOLA", "Tra voce e appetito"],["GOLF", "Sport di buche e nome da maglione"],["GONG", "Dichiara concluso il round"],["GOTO", "Barbaro che entro nella storia di Roma"]);
NEW.push(["GUAI", "Arrivano quando i conti non tornano"],["GUFO", "Notturno che secondo alcuni porta sfortuna"],["GURU", "Maestro che attira discepoli"],["IBIS", "Sacro sulle rive del Nilo antico"]);
NEW.push(["IDEA", "Scintilla prima dell'azione"],["IDRA", "Mostro dalle teste ricrescenti"],["ILEO", "Tratto intestinale da anatomisti"],["INCA", "Popolo andino prima dei conquistadores"]);
NEW.push(["IRAN", "Antica Persia sulle carte moderne"],["IRIS", "Fiore, occhio o messaggera divina"],["IRTO", "Pieno di punte o difficolta"],["ISBA", "Casa russa di legno"]);
NEW.push(["ISEO", "Lago lombardo meno citato del Como"],["ITER", "Percorso di pratiche e approvazioni"],["IUTA", "Fibra da sacchi ruvidi"],["JEEP", "Fuoristrada entrato nel linguaggio comune"]);
NEW.push(["JUDO", "Arte di leve e cadute"],["KAKI", "Frutto arancione che matura tardi"],["KIWI", "Uccello o frutto con lo stesso nome"],["LAGO", "Specchio d'acqua che non riflette sempre"]);
NEW.push(["LAMA", "Taglia, o sputa sulle Ande"],["LANA", "Fibra che fa caldo prima del maglione"],["LARI", "Dei domestici della Roma antica"],["LATO", "Non e il centro del poligono"]);
NEW.push(["LAVA", "Roccia che corre prima di indurire"],["LEGA", "Unisce metalli, squadre o Stati"],["LEVA", "Alza pesi o chiama soldati"],["LIDO", "Spiaggia con cabine e ombrelloni"]);
NEW.push(["LIMA", "Capitale andina e utensile abrasivo"],["LINO", "Fibra estiva da lenzuola"],["LIRA", "Moneta scomparsa e strumento antico"],["LITE", "Discussione che alza i toni"]);
NEW.push(["LOBO", "Parte molle o sezione anatomica"],["LODE", "Parola di approvazione o voto pieno"],["LODI", "Citta lombarda e plurale di elogi"],["LOGO", "Volto grafico di un marchio"]);
NEW.push(["LORO", "Appartiene ad altri"],["LOTO", "Fiore orientale e gioco di numeri"],["LUCE", "La cerca chi brancola"],["LUME", "Lampada d'altri tempi e intelletto"]);
NEW.push(["LUNA", "Satellite che cambia faccia"],["LUNE", "Capricci d'umore in forma plurale"],["LUPO", "Animale da fiaba e da branco"],["MAGO", "Fa sparire piu che spiegare"]);
NEW.push(["MAIA", "Madre di Hermes e nome primaverile"],["MALE", "Dolore o contrario morale"],["MANI", "Strumenti del tatto e del furto"],["MANO", "Aiuta, firma, prende e si alza"]);
NEW.push(["MARE", "Distesa che separa e unisce"],["MARI", "Pluralita di acque vaste"],["MELA", "Cadde a Newton, almeno nel racconto"],["MENO", "Segno che sottrae e avverbio comparativo"]);
NEW.push(["MENU", "Promette piatti prima che arrivino"],["META", "Arrivo del viaggio o del rugby"],["MIAO", "Verso domestico in quattro lettere"],["MICA", "Nega senza sembrare un no"]);
NEW.push(["MILO", "Isola della Venere senza braccia"],["MIMO", "Recita tacendo"],["MINA", "Puo stare sotto terra o in una matita"],["MIRA", "La prende chi vuole centrare"]);
NEW.push(["MITE", "Dolce di carattere, non di temperatura estrema"],["MITO", "Racconto antico o idolo moderno"],["MODA", "Passa proprio quando sembra imporsi"],["MODO", "Maniera, grammaticale o quotidiana"]);
NEW.push(["MOLA", "Macina o dente posteriore"],["MOLO", "Braccio di pietra nel porto"],["MORA", "Frutto del rovo o ritardo nei pagamenti"],["MORE", "Frutti del rovo e brune al plurale"]);
NEW.push(["MORO", "Scuro di capelli o personaggio storico"],["MOTO", "Due ruote e movimento"],["MULO", "Ibrido tenace da soma"],["MURO", "Divide, protegge o si salta"]);
NEW.push(["MUSA", "Ispiratrice che non scrive"],["MUTO", "Privo di voce o di parole"],["NANO", "Piccolo, ma anche stella densa"],["NASO", "Organo che fiuta e si immischia"]);
NEW.push(["NATO", "Alleanza atlantica o participio venuto al mondo"],["NAVE", "Casa che galleggia"],["NERO", "Colore, cronaca o caffe senza latte"],["NEVE", "Acqua che cade in silenzio bianco"]);
NEW.push(["NIDO", "Culla sospesa degli uccelli"],["NIKE", "Vittoria greca e marchio moderno"],["NOCE", "Guscio duro, albero e parte della mano"],["NODO", "Stringe corde e problemi"]);
NEW.push(["NOIA", "Tempo che pesa"],["NOLO", "Affitto di mezzi, non di case"],["NOME", "Identita in poche lettere"],["NORD", "Dove punta l'ago"]);
NEW.push(["NOTA", "Segno musicale o appunto"],["NOVE", "Numero che rovesciato inganna"],["NUBE", "Nuvola con tono poetico"],["NUCA", "Dietro la testa, sotto i capelli"]);
NEW.push(["NUDO", "Senza veli, anche in pittura"],["OASI", "Promessa d'acqua nel deserto"],["OBOE", "Legno d'orchestra dal timbro nasale"],["OCRA", "Giallo terroso da pittori"]);
NEW.push(["ODIN", "Dio nordico con corvi al seguito"],["ODIO", "Amore capovolto e avvelenato"],["OGAM", "Antico alfabeto irlandese"],["OGNI", "Distributivo che non lascia fuori nessuno"]);
NEW.push(["OLMO", "Albero caro ai viali"],["ONDA", "Si muove senza andare lontano"],["OPUS", "Opera in latino e in musica"],["ORCA", "Cetaceo che porta un nome ingiusto"]);
NEW.push(["ORCO", "Mostro delle fiabe e spauracchio"],["ORDA", "Folla piu minacciosa che ordinata"],["ORLO", "Confine di stoffa o precipizio"],["ORMA", "Firma lasciata dal passo"]);
NEW.push(["ORSA", "Costellazione e femmina del plantigrado"],["ORSO", "Plantigrado e uomo poco socievole"],["ORTO", "Piccolo regno di zappe"],["ORZO", "Cereale da zuppe e caffe senza caffe"]);
NEW.push(["OSSO", "Resta quando la polpa se ne va"],["OSTE", "Padrone di tavole e vino"],["OTTO", "Numero con due pance"],["PACE", "Assenza preziosa di conflitto"]);
NEW.push(["PAGA", "Arriva a fine mese, non sempre abbastanza"],["PAIO", "Due che fanno un'unita"],["PALA", "Ha un manico o gira nel vento"],["PALI", "Sostegni verticali e plurale da calcio"]);
NEW.push(["PALO", "Sta ritto: in campo puo negare il gol"],["PANE", "Cibo quotidiano e metafora di lavoro"],["PAPA", "Sovrano senza corona terrena"],["PARE", "Sembra o uguaglia"]);
NEW.push(["PARI", "Uguale o divisibile per due"],["PECE", "Nera e appiccicosa da calafati"],["PELO", "Puo stare sull'animale o sullo stomaco"],["PENA", "Castigo o compassione"]);
NEW.push(["PEPE", "Piccantezza da macinare"],["PERA", "Frutto con forma da lampadina"],["PERO", "Albero che porta un frutto a campana"],["PESO", "Lo sente chi porta o chi misura"]);
NEW.push(["PINO", "Conifera da pinoli e resina"],["POCO", "Quantita avara"],["POLO", "Estremo terrestre, sport o maglia"],["POMO", "Mela in lingua poetica"]);
NEW.push(["POSA", "Atteggiamento da ritratto o da pavimento"],["PRUA", "Davanti della nave, dove l'acqua si apre"],["PUMA", "Felino americano da salto"],["PUPA", "Bambola o ragazza in voce familiare"]);
NEW.push(["PURO", "Senza miscele ne macchie"],["QUIZ", "Domanda che promette premio"],["RAGU", "Sugo che richiede pazienza"],["RAID", "Incursione rapida e improvvisa"]);
NEW.push(["RAME", "Metallo rosso dei fili e dei paioli"],["RAMO", "Braccio d'albero o di famiglia"],["RAPA", "Radice da minestra povera"],["RARO", "Scarso, quindi ricercato"]);
NEW.push(["RASO", "Tessuto liscio o barba appena fatta"],["RATA", "Quota che torna ogni mese"],["RECA", "Porta con se in lingua formale"],["RENA", "Sabbia, con parola da lido antico"]);
NEW.push(["RENE", "Filtro naturale doppio"],["RENO", "Fiume d'Europa e fiume d'Emilia"],["RETE", "Cattura pesci, gol e dati"],["RIGA", "Linea, citta baltica o disciplina"]);
NEW.push(["RIMA", "Accordo finale tra versi"],["RISO", "Cereale che ride nel doppio senso"],["RITO", "Cerimonia fissata dalla tradizione"],["RIVA", "Confine fra acqua e terra"]);
NEW.push(["ROBA", "Cose senza catalogo"],["ROCK", "Chitarre, batteria e amplificatori"],["ROGO", "Fuoco che consuma in pubblico"],["ROMA", "Caput mundi in quattro lettere"]);
NEW.push(["ROSA", "Fiore, colore o elenco di nomi"],["ROVO", "Pianta spinosa da more"],["RUDE", "Ruvido nei modi"],["RUGA", "Segno del tempo sul volto"]);
NEW.push(["RUNA", "Lettera nordica da magia antica"],["SAGA", "Racconto lungo di stirpi e destini"],["SAIO", "Veste ruvida da frate"],["SALA", "Ambiente ampio, da cinema o palazzo"]);
NEW.push(["SALE", "Insaporisce e conserva"],["SANO", "Integro nel corpo o nel giudizio"],["SARI", "Abito femminile indiano"],["SCIA", "Traccia liquida, aerea o luminosa"]);
NEW.push(["SEBO", "Grasso cutaneo, non cucina"],["SEDE", "Luogo ufficiale o parte su cui si siede"],["SEGA", "Taglia, ma puo essere anche un cruccio"],["SEME", "Inizio botanico e carta da gioco"]);
NEW.push(["SENO", "Curve anatomiche e trigonometria"],["SERA", "Ora in cui la luce si ritira"],["SERI", "Poco inclini allo scherzo"],["SETA", "Fibra regale venuta dal baco"]);
NEW.push(["SETE", "Desiderio d'acqua o di potere"],["SILO", "Torre di grano"],["SITO", "Luogo reale o pagina in rete"],["SODA", "Acqua con bollicine, o caustica"]);
NEW.push(["SOFA", "Divano con nome un po' francese"],["SOIA", "Legume orientale da salsa e latte"],["SOLE", "Astro che non ha bisogno di lampioni"],["SOLO", "Senza compagnia o pezzo da virtuoso"]);
NEW.push(["STAR", "Stella importata dallo spettacolo"],["STOP", "Ordine breve che ferma"],["SUMO", "Lotta in cui il peso e disciplina"],["SURF", "Tavola che cavalca onde"]);
NEW.push(["TABU", "Divieto non sempre scritto"],["TALE", "Individuo non precisato"],["TANA", "Rifugio di chi si nasconde"],["TARA", "Peso che non conta"]);
NEW.push(["TECA", "Custodia trasparente da museo"],["TELA", "La prepara il ragno e la usa il pittore"],["TEMA", "Argomento da svolgere o motivo musicale"],["TESO", "Stirato o nervoso"]);
NEW.push(["TIFO", "Febbre da stadio o malattia storica"],["TIMO", "Aroma mediterraneo e ghiandola"],["TINO", "Vasca da cantina"],["TIPO", "Individuo generico o modello"]);
NEW.push(["TIRO", "Colpo, lancio o scherzo"],["TOGA", "Abito di foro e antica Roma"],["TONO", "Altezza della voce o sfumatura"],["TOPO", "Roditore e informatore in gergo"]);
NEW.push(["TORO", "Segno, bovino e piazza finanziaria"],["TOSI", "Ragazzi in parlata veneta"],["TRAM", "Rotaie urbane in breve"],["TRIO", "Tre che fanno gruppo"]);
NEW.push(["TUBA", "Cappello alto o basso strumento"],["TUBO", "Cilindro che porta acqua, gas o suoni"],["TUFO", "Pietra leggera nata dal fuoco"],["TUOI", "Possessivo plurale da confidenza"]);
NEW.push(["TUTA", "Abito intero da lavoro o palestra"],["UNNO", "Barbaro al seguito di Attila"],["UOVO", "Promessa di pulcino o ingrediente"],["URBE", "Citta con maiuscola latina"]);
NEW.push(["URLO", "Voce senza misura"],["URNA", "Contiene voti o ceneri"],["URTO", "Incontro brusco fra corpi"],["VAGO", "Impreciso o errante"]);
NEW.push(["VAIO", "Malattia scomparsa dai calendari vaccinali comuni"],["VALE", "Conta, costa o e diminutivo di Valentina"],["VANI", "Stanze o inutili"],["VANO", "Stanza o tentativo inutile"]);
NEW.push(["VARO", "Primo contatto della nave con l'acqua"],["VASI", "Recipienti o canali del corpo"],["VASO", "Sta sul davanzale o nel corpo"],["VATE", "Poeta con tono profetico"]);
NEW.push(["VEGA", "Stella della Lira e nome da fantascienza"],["VELA", "Tessuto che sfrutta il vento"],["VELO", "Copre senza nascondere del tutto"],["VENA", "Strada del sangue e dell'ispirazione"]);
NEW.push(["VERI", "Non falsi al plurale"],["VERO", "Non finto, ma spesso da provare"],["VETO", "No con forza istituzionale"],["VILE", "Basso di prezzo o d'animo"]);
NEW.push(["VINO", "Nasce dall'uva e migliora racconti"],["VISA", "Carta o visto, secondo la lingua"],["VISO", "Parte che tradisce emozioni"],["VITA", "Biografia, esistenza o filettatura"]);
NEW.push(["VITE", "Pianta da grappoli o piccola spirale"],["VIVO", "Acceso, presente o non morto"],["VOCE", "Suono umano e voce di elenco"],["VOCI", "Elementi d'elenco o suoni umani"]);
NEW.push(["VOGA", "Remo in movimento e moda passeggera"],["VOLO", "Viaggio senza toccare terra"],["VOTO", "Scelta in cabina o promessa religiosa"],["YOGA", "Disciplina che piega il corpo e il respiro"]);
NEW.push(["ZARA", "Citta dalmata e nome commerciale"],["ZELO", "Impegno che puo diventare eccesso"],["ZERO", "Numero che conta quando manca"],["ZEUS", "Padre olimpico con fulmini"]);
NEW.push(["ZONA", "Area con confini spesso incerti"]);

// ===================== 5 LETTERE (642 voci) =====================
NEW.push(["ABACO", "Calcolatore prima del calcolo elettronico"],["ABATE", "Superiore con saio e autorita"],["ABETE", "Conifera che finisce spesso addobbata"],["ABILE", "Sa fare senza far rumore"]);
NEW.push(["ACIDO", "Lo e il limone, ma anche un commento corrosivo"],["ACUTO", "Angolo non ottuso e ingegno pronto"],["ADONE", "Bello per antonomasia mitologica"],["AEREO", "Mezzo che ha pista ma non ruote come fine"]);
NEW.push(["AFIDE", "Piccolo nemico delle piante tenere"],["AGAVE", "Succulenta che puo finire in distillato messicano"],["AGILE", "Si muove senza far sentire il peso"],["AGONE", "Lotta, gara o pesce di lago"]);
NEW.push(["AIACE", "Eroe omerico dal nome breve"],["ALATO", "Dotato di cio che manca ai serpenti"],["ALBUM", "Raccolta da sfogliare o ascoltare"],["ALCOL", "Spirito che non e fantasma"]);
NEW.push(["ALIBI", "Altrove che salva l'imputato"],["ALITO", "Respiro quando diventa percepibile"],["ALONE", "Cerchio di luce o macchia"],["ALTRO", "Diverso, ma non necessariamente opposto"]);
NEW.push(["AMARO", "Sapore da espresso senza zucchero, o destino"],["AMBRA", "Resina fossile che imprigiona insetti"],["AMENO", "Piacevole in modo da cartolina"],["AMICO", "Alleato della vita privata"]);
NEW.push(["AMORE", "Ha fatto scrivere piu versi che contratti"],["ANETO", "Erba aromatica da cucina nordica"],["ANICE", "Profumo da sambuca"],["ANIMA", "Parte invisibile che i filosofi discutono"]);
NEW.push(["ANIMO", "Coraggio quando precede un punto esclamativo"],["ANODO", "Polo positivo, non sempre intuitivo"],["ANTRO", "Cavita che promette ombre"],["AORTA", "Grande via d'uscita dal cuore"]);
NEW.push(["APICE", "Punto alto che non e sempre fisico"],["APNEA", "Respiro sospeso per scelta o pericolo"],["ARENA", "Spazio di lotta, spettacolo o polemica"],["ARGON", "Gas nobile che non ama reagire"]);
NEW.push(["ARIEL", "Spirito shakespeariano e nome da satellite"],["AROMA", "Profumo che anticipa il gusto"],["ARPIA", "Mostro e insulto con ali antiche"],["ASCIA", "Ferro da taglio con manico lungo"]);
NEW.push(["ASILO", "Rifugio o scuola dei piu piccoli"],["ASINO", "Quadrupede paziente e insulto scolastico"],["ASOLA", "Occhiello in cui entra un bottone"],["ASPRO", "Poco dolce, al gusto o al carattere"]);
NEW.push(["ASSAI", "Molto, con sapore un po' letterario"],["ASTRO", "Brilla anche quando e solo una celebrita"],["ATENA", "Dea nata armata dalla testa di Zeus"],["ATOMO", "Unita minima prima che la fisica la complicasse"]);
NEW.push(["ATRIO", "Ambiente d'ingresso, tra fuori e dentro"],["AVARO", "Fa economia anche di sorrisi"],["AVENA", "Cereale da colazioni nordiche"],["AVIDO", "Vuole piu di quanto basti"]);
NEW.push(["AVVIO", "Primo impulso di un processo"],["AZOTO", "Gas che riempie l'aria senza farsi notare"],["BACCA", "Piccolo frutto da bosco o botanico"],["BAGNO", "Stanza, immersione o folla compatta"]);
NEW.push(["BALIA", "Nutrice e tutela temporanea"],["BALLO", "Lo si apre con le danze"],["BALZA", "Salto o fascia d'abito"],["BANCO", "Sta a scuola, in banca o al mercato"]);
NEW.push(["BARCA", "Ha chiglia e non ama l'asfalto"],["BARDO", "Poeta celtico da nebbie antiche"],["BASCO", "Copricapo piatto o abitante dei Pirenei"],["BEATO", "Felice in terra, ufficiale in cielo"]);
NEW.push(["BEFFA", "Inganno con sorriso amaro"],["BELLO", "Categoria estetica e complimento facile"],["BELVA", "Animale feroce e persona crudele"],["BENDA", "Nasconde una ferita o un occhio"]);
NEW.push(["BERTA", "Uccello marino e nome femminile d'altri tempi"],["BETTA", "Pesce combattente da acquario"],["BILIA", "Pallina da tavolo verde e umore antico"],["BIMBO", "Bambino detto con tenerezza"]);
NEW.push(["BIOMA", "Grande ambiente naturale"],["BIRRA", "Schiuma nel boccale"],["BISCA", "Gioco d'azzardo poco raccomandabile"],["BIVIO", "Due strade e una decisione"]);
NEW.push(["BOMBA", "Fa rumore, anche quando e una notizia"],["BORGO", "Paese dentro mura o fuori dal centro"],["BORSA", "Contiene oggetti o quotazioni"],["BOSCO", "Molti alberi senza viali"]);
NEW.push(["BOTTE", "Contenitore di vino o percosse"],["BRACE", "Fuoco che non fa piu fiamma"],["BRADO", "Libero nei campi, detto di bestiame"],["BRAVO", "Applauso o aggettivo da scolaro"]);
NEW.push(["BRIGA", "Fastidio che qualcuno si prende"],["BRINA", "Gelo sottile sul mattino"],["BRODO", "Base calda che consola malati e risotti"],["BRUNO", "Scuro, ma non nero"]);
NEW.push(["BUFFO", "Strano al punto da far sorridere"],["BURRO", "Grasso che si scioglie in padella"],["CACAO", "Seme amaro prima del cioccolato"],["CAIRO", "Metropoli sul Nilo"]);
NEW.push(["CALCE", "Piede del foglio o materiale da muratore"],["CALMO", "Tranquillo come mare senza vento"],["CALVO", "Privo di chioma, non di idee"],["CALZA", "Indumento che sale dal piede"]);
NEW.push(["CAMPO", "Terreno di gioco, studio o battaglia"],["CANNA", "Pianta cava, misura o parte d'arma"],["CANTO", "Voce ordinata in melodia"],["CAPRA", "Rumina, si arrampica e diventa insulto scolastico"]);
NEW.push(["CARIE", "Scavo indesiderato nel dente"],["CARNE", "Materia da macello e da teatro"],["CARPA", "Pesce d'acqua dolce e paziente"],["CARRO", "Veicolo che precede il motore"]);
NEW.push(["CARTA", "Foglio, mappa o promessa scritta"],["CASCO", "Protegge chi cade, o cade a fagiolo"],["CASTA", "Gruppo chiuso o donna illibata"],["CAUSA", "Motivo, processo o origine"]);
NEW.push(["CAVIA", "Animale da laboratorio e vittima di esperimenti"],["CELLA", "Piccolo vano, da monaco o detenuto"],["CERTO", "Sicuro, ma non sempre interessante"],["CERVO", "Porta corna senza colpa"]);
NEW.push(["CESTO", "Vimini che contiene"],["CHILO", "Mille grammi in parola comune"],["CHINA", "Inchiostro orientale o discesa"],["CICCA", "Residuo di fumo o cosa da poco"]);
NEW.push(["CIECO", "Non vede, ma puo guidare una fiducia"],["CIFRA", "Numero, somma o stile personale"],["CINTA", "Recinto, mura o cintura abbreviata"],["CIRCO", "Tenda di acrobati e pagliacci"]);
NEW.push(["CIUCO", "Asino in voce familiare"],["CLERO", "Corpo degli uomini d'altare"],["CLIMA", "Tempo medio, anche fra le persone"],["CLORO", "Elemento verde-giallo da piscine e chimici"]);
NEW.push(["COBRA", "Serpente che allarga il collo"],["COCCO", "Frutto duro e prediletto di qualcuno"],["COLLE", "Altura gentile, non ancora monte"],["COLLO", "Stringe camicie e bottiglie"]);
NEW.push(["COLMO", "Pieno al limite o battuta paradossale"],["COLPO", "Botta, tiro o impresa improvvisa"],["CONTE", "Nobile titolato sotto il marchese"],["CONTO", "Si paga, si tiene, si fa"]);
NEW.push(["COPPA", "Trofeo, bicchiere o salume"],["CORDA", "Si tende in musica, sport o nodo"],["CORNO", "Spunta sulla testa o suona in orchestra"],["CORPO", "Materia fisica e parte di testo"]);
NEW.push(["CORSA", "Competizione contro tempo o avversari"],["CORSO", "Viale, lezione o andamento"],["CORTE", "Palazzo regale o tribunale"],["CORVO", "Uccello nero da presagi letterari"]);
NEW.push(["COSMO", "Ordine universale in cinque lettere"],["COSTA", "Riva del mare e osso del torace"],["COSTO", "Prezzo non sempre monetario"],["CRETA", "Isola di Minosse e materiale da modellare"]);
NEW.push(["CROMO", "Metallo lucente da cromature"],["CRUDO", "Non passato dal fuoco, o brutale"],["CULLA", "Primo letto e origine"],["CUNEO", "Citta piemontese e solido a punta"]);
NEW.push(["CUOCO", "Professionista che regge fuochi"],["CUORE", "Muscolo, centro e simbolo sentimentale"],["CURVA", "Linea che rifiuta la rettitudine"],["DANNO", "Perdita che puo chiedere risarcimento"]);
NEW.push(["DANTE", "Sommo che fece parlare l'aldila in terzine"],["DANZA", "Movimento che obbedisce al ritmo"],["DARDO", "Freccia breve e aggressiva"],["DARIO", "Nome da re persiano e da amico qualunque"]);
NEW.push(["DELTA", "Lettera greca e foce ramificata"],["DENTE", "Taglia, morde, ingrana"],["DISCO", "Gira in musica e in geometria"],["DITTA", "Impresa col nome in insegna"]);
NEW.push(["DOGMA", "Verita che non gradisce discussioni"],["DOLCE", "Non amaro: puo chiudere il pasto"],["DONNA", "Figura femminile: nei romanzi spesso protagonista"],["DRAGO", "Mostro che custodisce e brucia"]);
NEW.push(["DUOMO", "Chiesa maggiore che da nome alla piazza"],["EBANO", "Legno nero da mobili preziosi"],["EDERA", "Rampicante ostinata sui muri"],["ELICA", "Gira per spingere aria o acqua"]);
NEW.push(["ELITE", "Pochi scelti, spesso molto visibili"],["EPOCA", "Periodo riconoscibile a posteriori"],["EREMO", "Solitudine abitata da preghiera"],["ESAME", "Prova che fa sudare anche da seduti"]);
NEW.push(["ESILE", "Sottile fino alla fragilita"],["ESITO", "Risultato quando la prova finisce"],["ESODO", "Partenza collettiva e libro biblico"],["ESTRO", "Capriccio creativo"]);
NEW.push(["ETICA", "Morale organizzata in filosofia"],["FABIO", "Nome proprio latino e familiare"],["FALCO", "Rapace addestrato per la caccia"],["FALDA", "Strato nascosto, di acqua o tessuto"]);
NEW.push(["FALSO", "Contraffatto o menzognero"],["FANGO", "Terra liquida che sporca e trattiene"],["FARSA", "Commedia o situazione ridicola"],["FASTO", "Lusso esibito nelle cerimonie"]);
NEW.push(["FAUNA", "Popolazione animale d'un luogo"],["FELCE", "Pianta antica senza fiori vistosi"],["FERMO", "Immobile, ma anche comune marchigiano"],["FERRO", "Metallo, attrezzo o cavallo da stiro"]);
NEW.push(["FESSO", "Sciocco in modo poco elegante"],["FESTA", "Giorno diverso dagli altri"],["FETTA", "Parte tagliata prima di servire"],["FIABA", "Narrativa con prove, magie e lieto fine"]);
NEW.push(["FIATO", "Serve a parlare e a resistere"],["FIBRA", "Filamento, tessuto o tenacia"],["FICUS", "Pianta da appartamento e da botanici"],["FIENO", "Erba secca da stalla"]);
NEW.push(["FIERA", "Mercato espositivo o belva orgogliosa"],["FINTO", "Recitato come vero"],["FIORE", "Organo vegetale e complimento"],["FIRMA", "Nome che vincola"]);
NEW.push(["FIUME", "Acqua che non resta ferma"],["FLORA", "Popolazione vegetale d'un luogo"],["FOLLA", "Molti corpi, poca distanza"],["FOLLE", "Senza ragione, ma con slancio"]);
NEW.push(["FOLTO", "Fitto, detto di capelli o boschi"],["FONDO", "Base, parte remota o denaro accantonato"],["FONTE", "Origine d'acqua o d'informazione"],["FORCA", "Attrezzo agricolo o patibolo"]);
NEW.push(["FORMA", "Aspetto, stampo o condizione fisica"],["FORNO", "Camera calda da pane e ceramica"],["FORTE", "Robusto, intenso o costruzione militare"],["FORZA", "Energia, potere o invito"]);
NEW.push(["FOSCO", "Scuro e poco rassicurante"],["FOSSA", "Scavo che inghiotte"],["FRANA", "La montagna quando cede"],["FRATE", "Religioso in saio"]);
NEW.push(["FRENO", "Trattiene ruote e impulsi"],["FRODE", "Inganno con vantaggio illecito"],["FUOCO", "Elemento che scalda, brucia e concentra"],["FURBO", "Capisce dove altri inciampano"]);
NEW.push(["FURIA", "Impetuosita che perde misura"],["FUSTO", "Tronco, bidone o bel tipo"],["GAMBA", "Arto e sostegno"],["GARBO", "Eleganza dei modi"]);
NEW.push(["GATTO", "Felino domestico che non obbedisce"],["GELSO", "Albero caro ai bachi da seta"],["GEMMA", "Pietra o promessa di foglia"],["GENIO", "Talento raro o spirito della lampada"]);
NEW.push(["GENOA", "Squadra ligure con nome inglese"],["GESSO", "Scrive alla lavagna e blocca le fratture"],["GESTO", "Movimento che parla"],["GETTO", "Flusso improvviso o colata"]);
NEW.push(["GHIRO", "Dormiglione proverbiale"],["GIADA", "Pietra verde d'Oriente"],["GIARA", "Grande vaso da olio o novelle"],["GILDA", "Associazione di mestiere e donna da cinema"]);
NEW.push(["GIOCO", "Ha regole anche quando diverte"],["GIOIA", "Allegrezza che puo diventare gioiello"],["GLOBO", "Sfera terrestre in miniatura"],["GNOMO", "Piccolo abitante di fiabe sotterranee"]);
NEW.push(["GOBBO", "Curvo di schiena o suggeritore teatrale"],["GOMMA", "Cancella, rimbalza o sigilla"],["GONNA", "Indumento che non ha gambe"],["GORGO", "Vortice che inghiotte"]);
NEW.push(["GRADO", "Misura, rango o gradino"],["GRAFO", "Rete di nodi per matematici"],["GRANO", "Cereale e vecchia unita di peso"],["GRECO", "Lingua, popolo e caffe ristretto"]);
NEW.push(["GRETO", "Letto asciutto di torrente"],["GRIDO", "Voce che rompe il silenzio"],["GRIFO", "Creatura con aquila e leone"],["GUADO", "Passaggio dove l'acqua concede"]);
NEW.push(["GUSTO", "Senso che giudica sapori e stile"],["IBERO", "Antico abitante di Spagna e Portogallo"],["IDOLO", "Oggetto di culto o di fan"],["IGLOO", "Casa di ghiaccio da immaginario polare"]);
NEW.push(["IMAGO", "Figura adulta dell'insetto, per entomologi"],["IMENE", "Dio nuziale o termine anatomico"],["INANE", "Vuoto d'efficacia, in tono letterario"],["INDIA", "Subcontinente di spezie e monsoni"]);
NEW.push(["IODIO", "Elemento da disinfettanti e tiroide"],["IRENE", "Nome che significa pace"],["IRIDE", "Arcobaleno nell'occhio"],["ISOLA", "Terra che il mare separa"]);
NEW.push(["JOLLY", "Carta senza ruolo fisso"],["LADRO", "Prende cio che non gli spetta"],["LAGNA", "Lamento che si allunga"],["LAMPO", "Luce brevissima prima del tuono"]);
NEW.push(["LAPIS", "Matita in parola scolastica antica"],["LARDO", "Grasso conservato in conca"],["LARGO", "Ampio, lento in musica"],["LARVA", "Forma provvisoria d'insetto"]);
NEW.push(["LASER", "Luce disciplinata in un raggio"],["LATTE", "Liquido bianco, non solo di mucca"],["LAURO", "Alloro da poeti e arrosti"],["LAUTO", "Ricco, detto spesso del pasto"]);
NEW.push(["LEGGE", "Comanda anche senza voce"],["LEGNO", "Materia viva diventata tavola"],["LEMBO", "Parte marginale di stoffa o terra"],["LEMMA", "Voce di dizionario e oggetto matematico"]);
NEW.push(["LENTO", "Opposto di rapido, ma anche tempo musicale"],["LEONE", "Felino e segno di fuoco"],["LESTO", "Rapido con sapore antico"],["LIBRO", "Oggetto che si apre per entrare altrove"]);
NEW.push(["LIETO", "Sereno, spesso in fine"],["LINEA", "Tratto, condotta o forma"],["LINFA", "Sangue vegetale, se si puo dire"],["LISCA", "Ostacolo sottile nel pesce"]);
NEW.push(["LISTA", "Elenco, striscia o candidatura"],["LITIO", "Metallo leggero da batterie"],["LIUTO", "Corde da musica antica"],["LOIRA", "Fiume dei castelli francesi"]);
NEW.push(["LOTTA", "Scontro regolato o quotidiano"],["LOTTO", "Gioco di numeri e terreno edificabile"],["LUCIA", "Nome manzoniano e luminosa santa"],["LUMEN", "Misura di luce o cavita anatomica"]);
NEW.push(["LUNGO", "Esteso, anche nel caffe"],["LUPUS", "Lupo latino e malattia autoimmune"],["LUSSO", "Superfluo costoso"],["LUTTO", "Dolore con abiti scuri"]);
NEW.push(["MACAO", "Citta del gioco alla foce del Fiume delle Perle"],["MACRO", "Grande come prefisso fotografico e informatico"],["MADIA", "Mobile rustico per pane e farina"],["MADRE", "Origine familiare e linguistica"]);
NEW.push(["MAGIA", "Effetto senza spiegazione apparente"],["MAGMA", "Roccia prima di diventare pietra"],["MAGRO", "Poco grasso o poco ricco"],["MALGA", "Alpeggio con latte e formaggi"]);
NEW.push(["MALTO", "Cereale germinato da birrai"],["MAMBO", "Ritmo caraibico da ballare"],["MAMMA", "Nome che spesso si impara per primo"],["MANGO", "Frutto tropicale e non manico"]);
NEW.push(["MANIA", "Fissazione che occupa la mente"],["MANTO", "Copertura regale o animale"],["MAORI", "Popolo polinesiano di Aotearoa"],["MARCA", "Confine, griffe o regione storica"]);
NEW.push(["MAREA", "Respiro periodico del mare"],["MARIO", "Nome comune e antico console romano"],["MARMO", "Pietra che gli scultori liberano"],["MARRA", "Zappa robusta da campi"]);
NEW.push(["MARTA", "Nome proprio e piccolo mustelide"],["MARZO", "Mese di vento e idi"],["MASSA", "Quantita, folla o proprieta fisica"],["MATTO", "Fuori di senno o finale degli scacchi"]);
NEW.push(["MAZZA", "Bastone da colpire o mazzo pesante"],["MEDIO", "Sta tra due estremi"],["MENSA", "Tavola comune e servizio aziendale"],["MENTA", "Profuma gomme, liquori e giardini"]);
NEW.push(["MENTO", "Parte del volto che si alza con orgoglio"],["MERCE", "Viaggia, si compra, si vende"],["MERLO", "Uccello nero o profilo di castello"],["MESSE", "Raccolto o funzioni religiose"]);
NEW.push(["MESTO", "Triste senza clamore"],["METRO", "Misura, verso o ferrovia sotterranea"],["MIELE", "Dolcezza fabbricata da api"],["MILZA", "Organo che pochi nominano volentieri"]);
NEW.push(["MIOPE", "Vede corto, anche in senso figurato"],["MIRRA", "Resina da re magi e profumi antichi"],["MIRTO", "Arbusto mediterraneo e liquore sardo"],["MISTO", "Non puro, non unico"]);
NEW.push(["MOGIO", "Triste e senza slancio"],["MOLLA", "Si comprime per reagire"],["MOLTO", "Quantita abbondante in una parola"],["MONDO", "Tutto cio che sta sotto il cielo"]);
NEW.push(["MONTE", "Rilievo, somma o mazzo di carte"],["MORBO", "Malattia con nome solenne"],["MORSA", "Stringe pezzi sul banco"],["MORSO", "Segno dei denti o pezzo del freno"]);
NEW.push(["MORTE", "Ultima soglia dei viventi"],["MOSCA", "Insetto e capitale"],["MOSSA", "Passaggio di gioco o astuzia"],["MOSTO", "Vino prima di diventarlo"]);
NEW.push(["MOTTO", "Frase breve che pretende memoria"],["MUCCA", "Ruminante da latte quotidiano"],["MUFFA", "Vita verde dove il cibo invecchia male"],["MULTA", "Prezzo d'una infrazione"]);
NEW.push(["MUSEO", "Dove il passato non dovrebbe prendere polvere"],["NADIR", "Punto opposto allo zenit"],["NANNA", "Sonno in lingua infantile"],["NAPPA", "Fiocco ornamentale o pelle pregiata"]);
NEW.push(["NEPAL", "Stato himalayano fra giganti"],["NERBO", "Vigore che sostiene"],["NETTO", "Pulito, chiaro o senza tara"],["NINFA", "Creatura d'acque e boschi"]);
NEW.push(["NOBEL", "Premio e dinamitardo svedese"],["NONNA", "Madre di un genitore"],["NONNO", "Padre di un genitore"],["NORMA", "Regola e opera di Bellini"]);
NEW.push(["NOTTE", "Meta oscura del giorno"],["NUORA", "Entra in famiglia sposando un figlio"],["NUOTO", "Sport senza appoggi"],["NUOVO", "Non ancora consumato dal tempo"]);
NEW.push(["OBESO", "Eccessivamente pesante, clinicamente"],["ODEON", "Piccolo teatro antico o cinema d'epoca"],["OMERO", "Poeta cieco e osso del braccio"],["OMINO", "Piccolo uomo disegnato"]);
NEW.push(["ONERE", "Peso piu giuridico che fisico"],["OPACO", "Non lascia passare chiaramente la luce"],["OPALE", "Pietra dai lampi lattiginosi"],["OPERA", "Lavoro, teatro o prodotto d'artista"]);
NEW.push(["ORATA", "Pesce dal nome dorato"],["ORFEO", "Cantore che scese agli inferi"],["ORICE", "Antilope dalle corna lunghe"],["OSCAR", "Premio che pesa poco ma vale molto"]);
NEW.push(["OSSEO", "Di scheletro"],["OSTIA", "Lido romano e particola consacrata"],["OVEST", "Punto dove il sole si congeda"],["OVILE", "Casa lanosa, per cosi dire"]);
NEW.push(["OVULO", "Cellula femminile o forma farmaceutica"],["OZONO", "Tre atomi d'ossigeno in quota"],["PADRE", "Genitore, frate o origine"],["PALCO", "Scena rialzata o corna di cervo"]);
NEW.push(["PALIO", "Drappo conteso da contrade"],["PALLA", "Sfera da gioco o bugia"],["PALMA", "Pianta da datteri e mano aperta"],["PALMO", "Misura a mano aperta"]);
NEW.push(["PANDA", "Bianco e nero senza essere scacchiera"],["PANNA", "Crema dolce da montare"],["PANNO", "Stoffa, ma anche questione nei panni"],["PARCO", "Giardino pubblico o moderato nello spendere"]);
NEW.push(["PAREO", "Telo da spiaggia che si annoda"],["PARMA", "Citta di prosciutto e teatro"],["PASSO", "Andatura, valico o brano"],["PASTA", "Impasto, carattere o primo piatto"]);
NEW.push(["PATIO", "Cortile spagnolo entrato nelle case"],["PAURA", "Emozione che stringe prima del pericolo"],["PAUSA", "Intervallo in cui il tempo respira"],["PEGNO", "Garanzia lasciata in cambio"]);
NEW.push(["PELLE", "Confine sensibile del corpo"],["PENNA", "Scrive, vola o finisce sul cappello"],["PERLA", "Goccia preziosa d'ostrica"],["PESCA", "Frutto o attivita con lenza"]);
NEW.push(["PESCE", "Animale che sa stare a galla senza saperlo"],["PESTE", "Male storico o condimento ligure"],["PETTO", "Parte anteriore che si gonfia d'orgoglio"],["PEZZO", "Parte, brano o articolo"]);
NEW.push(["PIAGA", "Ferita aperta o flagello sociale"],["PIANO", "Strumento, progetto o livello"],["PIAVE", "Fiume sacro alla patria"],["PIEDE", "Base del corpo e del verso"]);
NEW.push(["PIEGA", "Svolta del tessuto o dei capelli"],["PIENO", "Senza vuoti, anche troppo"],["PILAF", "Riso cotto all'orientale"],["PINNA", "Arto del nuoto senza dita"]);
NEW.push(["PINZA", "Stringe senza abbracciare"],["PIOLO", "Gradino minuto da scala"],["PIREX", "Vetro che sopporta il forno"],["PISTA", "Traccia da seguire o luogo da correre"]);
NEW.push(["PIZZA", "Disco da forno con infinite varianti"],["PLEBE", "Popolo romano senza patriziato"],["PODIO", "Tre gradini per pochi"],["POEMA", "Versi lunghi e ambiziosi"]);
NEW.push(["POETA", "Mestiere di chi fa parlare i versi"],["POLIO", "Malattia combattuta dai vaccini"],["POLLO", "Animale da arrosto e ingenuo"],["POLPA", "Parte morbida e utile"]);
NEW.push(["POLPO", "Ha tentacoli e memoria inattesa"],["POLSO", "Dove il battito si lascia interrogare"],["POMPA", "Spinge liquidi e gonfia solennita"],["PONTE", "Unisce rive, denti o giorni festivi"]);
NEW.push(["PORCO", "Maiale in forma ruvida"],["PORRO", "Ortaggio a strati e escrescenza cutanea"],["PORTA", "Varco, ruolo calcistico o mano di carte"],["PORTO", "Rifugio di navi e bicchiere liquoroso"]);
NEW.push(["POSTA", "Lettere, puntata o posizione"],["POSTO", "Luogo occupabile o lavoro"],["POZZO", "Buca verticale in cerca d'acqua"],["PRATO", "Erba distesa, anche in Toscana"]);
NEW.push(["PREDA", "Chi e cercato dal cacciatore"],["PREGO", "Cortesia dopo un grazie"],["PRESA", "Attacco, corrente o conquista"],["PRETE", "Uomo d'altare"]);
NEW.push(["PRIMO", "Davanti a tutti o piatto iniziale"],["PRODE", "Coraggioso con sapore epico"],["PROSA", "Scrittura che non va a capo per canto"],["PROVA", "Tentativo che puo diventare esame"]);
NEW.push(["PUGNO", "Mano chiusa, colpo o quantita"],["PULCE", "Insetto saltatore e dubbio mentale"],["PUNTA", "Estremita, ballerina o attaccante"],["PUNTO", "Segno minimo che puo chiudere"]);
NEW.push(["PUZZA", "Odore che denuncia"],["QUOTA", "Parte assegnata o altezza"],["RADAR", "Occhio che vede con onde"],["RADIO", "Parla senza farsi vedere"]);
NEW.push(["RAGIA", "Resina che profuma di bosco"],["RAGNO", "Tessitore con otto zampe"],["RAMEN", "Zuppa giapponese da sorbire"],["RAMPA", "Salita che aiuta o affatica"]);
NEW.push(["RANCH", "Fattoria da immaginario western"],["RANGO", "Grado sociale o militare"],["RASPA", "Lima grossolana da falegname"],["RATTO", "Rapimento o roditore, secondo contesto"]);
NEW.push(["RAZZA", "Specie, stirpe o pesce piatto"],["RAZZO", "Sale con fuoco sotto"],["REALE", "Da re o autentico"],["REBUS", "Enigma fatto d'immagini e sillabe"]);
NEW.push(["REGIA", "Direzione dietro le quinte"],["REGNO", "Territorio di corona o natura"],["RESTO", "Avanzo e spiccioli"],["RETTA", "Linea senza esitazioni"]);
NEW.push(["RICCO", "Ha molto, non solo denaro"],["RIONE", "Quartiere con identita propria"],["RISMA", "Pacco da ufficio, non carattere"],["ROBOT", "Macchina che obbedisce a istruzioni"]);
NEW.push(["ROCCA", "Fortezza e utensile della filatrice"],["RODEO", "Spettacolo dove il cavallo non collabora"],["RONDO", "Forma musicale che ritorna"],["ROSEO", "Ottimistico in tinta chiara"]);
NEW.push(["ROSPO", "Anfibio poco principesco"],["ROSSO", "Colore di sangue, stop e vergogna"],["ROTTA", "Percorso nautico o cosa spezzata"],["RUGBY", "Sport con palla ovale"]);
NEW.push(["RULLO", "Cilindro che comprime o fa rumore"],["RUOLO", "Parte assegnata a teatro e nella vita"],["RUOTA", "Gira, sostiene e decide la fortuna"],["RUSPA", "Macchina che spiana e sposta"]);
NEW.push(["SACCO", "Contenitore, quantita o saccheggio"],["SAGRA", "Festa di paese con profumo di cucina"],["SALDO", "Pagamento finale o sconto stagionale"],["SALMA", "Corpo quando la vita e assente"]);
NEW.push(["SALMO", "Canto biblico numerato"],["SALSA", "Condimento e ritmo latino"],["SALTO", "Interruzione o balzo"],["SAMBA", "Ritmo brasiliano da carnevale"]);
NEW.push(["SANTO", "Ha aureola e calendario"],["SARTO", "Costruisce abiti su corpi reali"],["SASSO", "Pietra piccola ma contundente"],["SAUNA", "Caldo secco preso per benessere"]);
NEW.push(["SCALA", "Sale, misura e organizza note"],["SCALO", "Fermata di viaggio o porto secondario"],["SCENA", "Parte del teatro e della vita"],["SCOPA", "Pulisce o si gioca a carte"]);
NEW.push(["SCOPO", "Fine che orienta i mezzi"],["SCUDO", "Difesa antica e moneta scomparsa"],["SECCO", "Senza acqua o senza replica"],["SEDIA", "Mobile con schienale e quattro zampe"]);
NEW.push(["SEGNO", "Traccia, simbolo o destino zodiacale"],["SELVA", "Bosco fitto e dantesco"],["SENSO", "Direzione, significato o facolta"],["SERPE", "Rettile strisciante in veste poetica"]);
NEW.push(["SERVO", "Domestico senza liberta"],["SETTE", "Numero da nani, colli e note"],["SETTO", "Parete divisoria, anche nel naso"],["SFERA", "Solido senza spigoli"]);
NEW.push(["SFIDA", "Invito a misurarsi"],["SIEPE", "Confine verde che Leopardi guardava"],["SIGLA", "Nome accorciato in iniziali"],["SIRIO", "Stella del Cane, luminosissima"]);
NEW.push(["SOGNO", "Visione notturna o desiderio"],["SOLCO", "Traccia lasciata dall'aratro o dal tempo"],["SOLDO", "Moneta minima e vecchio stipendio"],["SONDA", "Esplora dove l'uomo non arriva"]);
NEW.push(["SONNO", "Debito che non si paga in banca"],["SORBO", "Albero dai frutti aspri"],["SORDO", "Non sente, o non fa rumore"],["SORGO", "Cereale resistente al secco"]);
NEW.push(["SORTE", "Destino o estrazione"],["SOSTA", "Fermata senza fine viaggio"],["SPADA", "Lama nobile da duello"],["SPAGO", "Filo rustico da pacchi e cucina"]);
NEW.push(["SPESA", "Costo o carrello pieno"],["SPIGA", "Orecchio del grano"],["SPINA", "Punge, collega corrente o sta nel pesce"],["SPOLA", "Correva nel telaio"]);
NEW.push(["SPORT", "Gioco serio con classifiche"],["SPOSA", "Protagonista in bianco, almeno per tradizione"],["SPUMA", "Schiuma piu elegante"],["STILE", "Modo personale e colonna sottile"]);
NEW.push(["STIVA", "Ventre della nave per il carico"],["STOLA", "Fascia sacra o elegante"],["STRIA", "Linea sottile e lunga"],["STUFA", "Riscalda, ma come aggettivo si e stancata"]);
NEW.push(["SUINO", "Relativo al maiale"],["SUONO", "Vibrazione che l'orecchio traduce"],["SUORA", "Donna di velo e convento"],["SVAGO", "Tempo sottratto al dovere"]);
NEW.push(["TACCO", "Rialza scarpe e colpisce nel calcio"],["TAIGA", "Foresta fredda di conifere"],["TANGO", "Ballo nato sul Rio de la Plata"],["TARDO", "Lento ad arrivare o capire"]);
NEW.push(["TARGA", "Nome metallico dell'auto o del premio"],["TARLO", "Rode legno e pensieri"],["TASCA", "Piccolo nascondiglio cucito"],["TASSO", "Animale, albero o percentuale"]);
NEW.push(["TASTO", "Si preme per musica o lettere"],["TEINA", "La caffeina quando sta nel te"],["TEMPO", "Passa, si misura, si perde"],["TENDA", "Riparo di tela o cortina domestica"]);
NEW.push(["TERME", "Acque calde e relax romano"],["TERNO", "Tre numeri fortunati al lotto"],["TERRA", "Pianeta, suolo o elemento"],["TERZO", "Viene dopo due, ma puo essere estraneo"]);
NEW.push(["TESTA", "Comanda il corpo e apre le classifiche"],["TETTO", "Copre la casa e limita la spesa"],["TIGRE", "Felino rigato e aggressivo"],["TILDE", "Segno ondulato sopra certe lettere"]);
NEW.push(["TINTA", "Colore steso o naturale"],["TIRSO", "Bastone sacro a Dioniso"],["TOLDO", "Copertura di tela su barche e terrazze"],["TOMBA", "Casa finale e verbo che precipita"]);
NEW.push(["TONDO", "Circolare, ma anche segno grafico"],["TONFO", "Caduta che si sente"],["TONNO", "Pesce grande che finisce in scatola"],["TOPPA", "Riparo di stoffa o errore rimediato male"]);
NEW.push(["TORBA", "Terra scura da paludi e giardinieri"],["TORRE", "Si arrocca negli scacchi o pende a Pisa"],["TORTA", "Dolce da candeline e fette"],["TORTO", "Ragione perduta"]);
NEW.push(["TOSSE", "Rumore del raffreddore"],["TRAMA", "Intreccio di fili o di storia"],["TRAVE", "Sostegno orizzontale e pagliuzza evangelica"],["TRENO", "Serpente di vagoni"]);
NEW.push(["TRIBU", "Comunita regolata da parentela"],["TRONO", "Sedia che vale un regno"],["TROTA", "Pesce da torrente e lenza"],["TULLE", "Velo leggerissimo da spose e teatri"]);
NEW.push(["TUONO", "Voce del temporale"],["TURBA", "Folla agitata o disturbo"],["TURNO", "Quota di tempo in ordine"],["UDITO", "Senso che lavora nel silenzio"]);
NEW.push(["UGOLA", "Pendolo in fondo alla bocca"],["ULIVO", "Albero di pace e olio"],["UMORE", "Stato d'animo o liquido corporeo"],["USURA", "Interesse che consuma chi deve"]);
NEW.push(["UTILE", "Serve, o resta dopo i costi"],["VALCO", "Passaggio fra monti"],["VALLE", "Depressione fra rilievi"],["VANGA", "Attrezzo che entra nella terra"]);
NEW.push(["VARCO", "Apertura che consente il passaggio"],["VARIO", "Non uguale a se stesso"],["VELIA", "Nome antico e citta della Magna Grecia"],["VENTO", "Aria quando decide di muoversi"]);
NEW.push(["VERBO", "Parola che porta l'azione"],["VERDE", "Colore di erba, speranza e semaforo"],["VERGA", "Bastone, ramo o scrittore siciliano"],["VERME", "Abitante del terreno e del dubbio"]);
NEW.push(["VERSO", "Riga poetica, direzione o grido animale"],["VESPA", "Punge, ronza o corre su due ruote"],["VESTE", "Abito, ma anche funzione"],["VETRO", "Solido trasparente e fragile"]);
NEW.push(["VETTA", "Cima che non concede oltre"],["VIALE", "Strada con alberi e passeggio"],["VIDEO", "Immagine in movimento, non per forza film"],["VIGNA", "Filari da vendemmia"]);
NEW.push(["VILLA", "Casa signorile fuori dal rumore"],["VINCA", "Pianta ornamentale e forma di vincere"],["VIOLA", "Colore, fiore o strumento"],["VIRGO", "Costellazione zodiacale latina"]);
NEW.push(["VIRUS", "Minuscolo invasore di cellule e computer"],["VISTA", "Senso e panorama"],["VIZIO", "Abitudine cattiva o difetto giuridico"],["VOLTO", "Faccia che si legge"]);
NEW.push(["ZAINO", "Compagno sulle spalle"],["ZAMPA", "Arto non umano"],["ZANNA", "Dente che sporge come arma"],["ZAPPA", "Attrezzo che rompe la terra"]);
NEW.push(["ZEBRA", "Cavallo in pigiama a righe"],["ZENIT", "Punto piu alto sopra la testa"],["ZINCO", "Metallo contro ruggine e carenze"],["ZOLFO", "Elemento giallo dall'odore infernale"]);
NEW.push(["ZORRO", "Maschera con firma a zeta"],["ZUPPA", "Piatto liquido che accoglie pane"]);

// ===================== 6 LETTERE (260 voci) =====================
NEW.push(["ABISSO", "Profondita che fa perdere la misura"],["ACERBO", "Non maturo, anche nel giudizio"],["ACULEO", "Punta naturale da difesa"],["ADAGIO", "Lento in musica e proverbio breve"]);
NEW.push(["AIRONE", "Uccello d'acqua dal collo paziente"],["ALCOVA", "Letto nascosto con parola antica"],["ALISEO", "Vento regolare da naviganti oceanici"],["ALLORO", "Corona di poeti e aroma da arrosto"]);
NEW.push(["AMBITO", "Campo circoscritto, non sempre recintato"],["AMLETO", "Principe del dubbio teatrale"],["ANCORA", "Tiene ferma una nave e, in grammatica, rinvia"],["ANELLO", "Cerchio da dito, catena o sport"]);
NEW.push(["ANFORA", "Vaso antico con due braccia"],["ANGELO", "Messaggero con ali nelle immagini sacre"],["ANGINA", "Male di gola dal nome medico"],["ANGOLO", "Dove due linee smettono di essere parallele"]);
NEW.push(["AQUILA", "Rapace imperiale e citta abruzzese"],["ARALDO", "Annuncia prima che parlino i potenti"],["ARDORE", "Calore che passa dai fuochi agli animi"],["ARGINE", "Limite che il fiume non dovrebbe superare"]);
NEW.push(["ARIETE", "Segno zodiacale e macchina d'assedio"],["ARNESE", "Attrezzo, ma detto anche di persona poco raccomandabile"],["ATENEO", "Universita con nome greco"],["AURORA", "Luce prima del giorno pieno"]);
NEW.push(["AVORIO", "Bianco prezioso e controverso"],["AVVISO", "Segnale che precede guai o notizie"],["AZALEA", "Fiorisce in vaso piu che nei romanzi"],["AZIONE", "Mossa, atto o quota societaria"]);
NEW.push(["BACINO", "Parte del corpo o conca d'acqua"],["BALENA", "Enorme cetaceo che in Pinocchio fa paura"],["BANANA", "Frutto curvo da buccia scivolosa"],["BARILE", "Misura da petrolio e contenitore"]);
NEW.push(["BIANCO", "Colore che sulla pagina aspetta parole"],["BIFORA", "Finestra medievale divisa in due"],["BILICO", "Equilibrio che non rassicura"],["BISCIA", "Serpente modesto, spesso innocuo"]);
NEW.push(["BREZZA", "Vento che non vuole fare paura"],["BROCCA", "Recipiente con manico e beccuccio"],["BRONZO", "Terzo gradino del podio e lega antica"],["BUFALO", "Bovino da mozzarella campana"]);
NEW.push(["CACCIA", "Insegue prede, o velivoli nemici"],["CALCIO", "Sport popolare e elemento chimico"],["CAMINO", "Focolare con via d'uscita per il fumo"],["CANALE", "Acqua guidata o emittente televisiva"]);
NEW.push(["CAROTA", "Radice arancione e promessa al somaro"],["CATENA", "Serie di anelli, monti o obblighi"],["CENERE", "Quel che resta del fuoco"],["CHIAVE", "Apre serrature e soluzioni"]);
NEW.push(["CHIESA", "Edificio, istituzione o comunita di fedeli"],["CHIODO", "Tiene appeso o si fissa in testa"],["CINEMA", "Arte che si guarda al buio"],["CIUFFO", "Capelli che sfuggono all'ordine"]);
NEW.push(["CODICE", "Sistema di segni, norme o segreti"],["COFANO", "Copre motori o custodisce oggetti"],["COLORE", "Non esiste al buio, ma si nomina sempre"],["COMETA", "Astro con coda scenografica"]);
NEW.push(["COMODO", "Confortevole o privo di fatica"],["CORONA", "Sta sul capo, nel rosario o in numismatica"],["COTONE", "Fibra bianca da campi e armadi"],["CUCINA", "Luogo, arte e tradizione gastronomica"]);
NEW.push(["DECORO", "Dignita delle forme e dei comportamenti"],["DENARO", "Mezzo di scambio e vecchio seme di carte"],["DERIVA", "Spostamento senza governo"],["DIESEL", "Motore e carburante dal nome d'inventore"]);
NEW.push(["DOGANA", "Confine dove le merci dichiarano"],["DOMINO", "Tessere che cadono anche per effetto"],["DRAPPO", "Stoffa solenne da cerimonia"],["EFFIGE", "Immagine ufficiale da moneta o medaglia"]);
NEW.push(["ELEGIA", "Canto malinconico da antichi poeti"],["ELISIR", "Liquido miracoloso da alchimisti"],["ENIGMA", "Domanda che si difende dalla risposta"],["ENZIMA", "Lavora nelle cellule senza consumarsi"]);
NEW.push(["ERCOLE", "Forza mitologica in sei lettere"],["ERESIA", "Idea religiosa fuori dal solco"],["ERMETE", "Dio dei messaggi e delle soglie"],["ERRORE", "Deviazione dalla risposta giusta"]);
NEW.push(["ESTATE", "Stagione che promette ferie e zanzare"],["FABBRO", "Batte il ferro finche e caldo"],["FAGGIO", "Albero montano da boschi freschi"],["FALENA", "Farfalla notturna attratta dal lume"]);
NEW.push(["FANALE", "Occhio di veicolo o porto"],["FARINA", "Polvere che diventa pane"],["FATICA", "Sforzo che pesa sui muscoli"],["FAVOLA", "Racconto breve con morale finale"]);
NEW.push(["FEBBRE", "Calore che il termometro denuncia"],["FENICE", "Uccello che fa della cenere un ritorno"],["FERITA", "Apertura dolorosa nella pelle o nell'orgoglio"],["FIASCO", "Bottiglia panciuta o insuccesso"]);
NEW.push(["FIBBIA", "Tiene ferma la cintura"],["FIGURA", "Forma, immagine o brutta impressione"],["FINALE", "Ultimo atto o partita decisiva"],["FIONDA", "Lancia sassi senza polvere da sparo"]);
NEW.push(["FISICA", "Studia materia, energia e imprevisti scolastici"],["FLAUTO", "Fiato che canta diritto"],["FOGLIA", "Pagina vegetale"],["FRONDA", "Ramo con foglie, spesso da riparo"]);
NEW.push(["GABBIA", "Limite a sbarre"],["GALERA", "Nave antica o carcere"],["GELATO", "Dolce che teme il sole"],["GENERE", "Categoria, sesso grammaticale o stile"]);
NEW.push(["GHETTO", "Quartiere imposto dalla storia"],["GIACCA", "Capo che completa un abito"],["GIRINO", "Rana prima di avere zampe"],["GIUGNO", "Mese che apre l'estate scolastica"]);
NEW.push(["GOMITO", "Piega del braccio e colpo scorretto"],["GRAPPA", "Distillato che nasce dalle vinacce"],["GRILLO", "Insetto canterino e coscienza di Pinocchio"],["GROTTA", "Cavita naturale da stalattiti"]);
NEW.push(["GRUPPO", "Insieme piu organizzato della folla"],["GUAINA", "Rivestimento che protegge e contiene"],["GUANTO", "Indumento a dita"],["IGUANA", "Rettile da teca tropicale"]);
NEW.push(["IMBUTO", "Fa entrare il largo nello stretto"],["INCISO", "Frase laterale o segno scavato"],["INDACO", "Blu profondo fra cielo e viola"],["INERTE", "Non reagisce, in chimica o nella vita"]);
NEW.push(["LACCIO", "Stringe scarpe e trappole"],["LAGUNA", "Acqua bassa tra terra e mare"],["LATITA", "Manca mentre dovrebbe esserci"],["LECCIO", "Quercia sempreverde mediterranea"]);
NEW.push(["LEGAME", "Vincolo che tiene insieme"],["LEGGIO", "Supporto da lettori in piedi"],["LIMONE", "Agrume aspro e colore chiaro"],["LINGUA", "Organo, idioma e confine culturale"]);
NEW.push(["LUCCIO", "Predatore d'acqua dolce"],["LUMACA", "Viaggia lenta lasciando firma lucida"],["MAGLIA", "Indumento, rete o punto lavorato"],["MANICA", "Parte del vestito e cerchia di complici"]);
NEW.push(["MANTRA", "Formula ripetuta fino a diventare ritmo"],["MEDUSA", "Mostro che pietrifica e animale urticante"],["MELONE", "Frutto estivo che si sceglie a colpi"],["METODO", "Ordine applicato al fare"]);
NEW.push(["MIMOSA", "Fiore giallo simbolico a marzo"],["MISURA", "Limite, taglia o operazione col metro"],["MOBILE", "Arredo, o non fisso"],["MONACO", "Religioso e abitante di un principato"]);
NEW.push(["MONILE", "Gioiello da collo o da polso"],["MORALE", "Insegnamento finale o disciplina dei costumi"],["MOTORE", "Trasforma energia in movimento"],["MULINO", "Casa delle macine"]);
NEW.push(["NEBBIA", "Fa sparire il paesaggio senza portarlo via"],["NEMICO", "Avversario senza sportivita"],["NIENTE", "Vuoto in forma di parola"],["NINFEO", "Fontana monumentale d'ispirazione antica"]);
NEW.push(["NIPOTE", "Parente che puo confondere generazioni"],["NOMADE", "Non mette radici in un indirizzo"],["NUVOLA", "Acqua sospesa che viaggia in cielo"],["OCEANO", "Mare che ha superato ogni misura"]);
NEW.push(["OFFESA", "Ferita fatta con parole"],["ORDITO", "La parte ferma della tela"],["ORTICA", "Pianta che punisce chi la sfiora"],["OSCURO", "Poco illuminato o poco chiaro"]);
NEW.push(["OTTONE", "Lega gialla da strumenti e maniglie"],["PALUDE", "Acqua che ristagna e trattiene"],["PANINO", "Due fette con qualcosa in mezzo"],["PARETE", "Confine verticale di una stanza o di roccia"]);
NEW.push(["PAROLA", "Unita minima del discorso con senso"],["PATATA", "Tubero da campo e da frittura"],["PAVONE", "Fa ruota per vanita naturale"],["PEDALE", "Lo spinge il ciclista e il pianista"]);
NEW.push(["PEDINA", "Piccolo pezzo che puo decidere la partita"],["PEPITA", "Oro ancora rozzo"],["PETALO", "Foglia colorata del fiore"],["PIANTA", "Vegetale, mappa o lamento"]);
NEW.push(["PIATTO", "Stoviglia, portata o poco mosso"],["PIAZZA", "Vuoto urbano dove la citta si incontra"],["PIETRA", "Materiale duro e memoria incisa"],["PILOTA", "Guida mezzi che non sempre toccano terra"]);
NEW.push(["PINOLO", "Seme piccolo da pesto e dolci"],["PIRATA", "Fuorilegge di mare e di copie"],["PIROGA", "Canoa scavata in un tronco"],["PITONE", "Serpente che stringe piu che mordere"]);
NEW.push(["POMATA", "Unguento da spalmare"],["POTERE", "Facolta, autorita o verbo irregolare"],["PRANZO", "Pasto che spezza la giornata"],["PRISMA", "Solido che divide la luce"]);
NEW.push(["PUGILE", "Professionista dei guanti chiusi"],["QUADRO", "Dipinto, schema o situazione"],["QUIETE", "Calma che puo precedere la tempesta"],["RABBIA", "Collera e malattia trasmessa da morsi"]);
NEW.push(["RAPACE", "Predatore con ali e artigli"],["RASOIO", "Lama quotidiana da barba"],["REDINE", "Cinghia che guida il cavallo"],["REGOLA", "Norma, strumento e ciclo"]);
NEW.push(["REMORA", "Pesce che si attacca e freno morale"],["RICAMO", "Disegno fatto col filo"],["RICCIO", "Punge a terra o in mare, si arriccia in testa"],["RIPOSO", "Intervallo che restituisce forza"]);
NEW.push(["RISATA", "Scoppio sonoro di buonumore"],["RIVALE", "Avversario con lo stesso obiettivo"],["ROCCIA", "Pietra compatta e carattere saldo"],["ROVERE", "Quercia da botti e mobili"]);
NEW.push(["ROVINA", "Crollo, resto antico o disastro"],["RUMORE", "Suono senza discrezione"],["SABBIA", "Terra finissima che misura clessidre"],["SAGOMA", "Contorno riconoscibile senza dettagli"]);
NEW.push(["SALAME", "Insaccato e ingenuo in gergo"],["SALICE", "Albero che piange senza dolore"],["SALONE", "Sala grande, spesso da esposizione"],["SALUTO", "Gesto che apre o chiude un incontro"]);
NEW.push(["SAPONE", "Fa schiuma contro lo sporco"],["SAPORE", "Giudizio della lingua e della memoria"],["SCATTO", "Balzo, foto o aumento improvviso"],["SCHEDA", "Supporto di dati, voto o gioco"]);
NEW.push(["SCIAME", "Folla alata e compatta"],["SEDANO", "Costa verde da soffritto"],["SESAMO", "Seme e parola magica con apriti"],["SFINGE", "Enigma con corpo di leone"]);
NEW.push(["SILURO", "Pesce elettrico o arma navale"],["SIRENA", "Chiama i marinai o avverte in strada"],["SLITTA", "Veicolo che preferisce neve e renne"],["SOFFIO", "Respiro leggero o impulso improvviso"]);
NEW.push(["SOGLIA", "Limite da varcare"],["SOLAIO", "Piano alto, spesso pieno di cose vecchie"],["SPALLA", "Sostegno, lato o aiutante comico"],["SPECIE", "Categoria dei viventi o avverbio incerto"]);
NEW.push(["SQUALO", "Predatore marino e finanziario"],["STAGNO", "Acqua ferma o metallo saldato"],["STALLA", "Alloggio bovino e memoria natalizia"],["STANZA", "Vano domestico o strofa"]);
NEW.push(["STELLA", "Luce celeste e fama terrena"],["STORIA", "Racconto, passato o relazione"],["STRADA", "Percorso materiale e modo per riuscire"],["STREGA", "Figura da rogo, fiaba e scopa"]);
NEW.push(["STUCCO", "Riempie crepe e imita marmi"],["SUDORE", "Sale sulla pelle per caldo o sforzo"],["TEGAME", "Parente largo della pentola"],["TEMPIO", "Luogo sacro di dei o muscoli"]);
NEW.push(["TENORE", "Voce alta maschile e contenuto"],["TEORIA", "Fila, ipotesi o sistema"],["TESORO", "Ricchezza nascosta e vezzeggiativo"],["TIMONE", "Guida barche e direzioni"]);
NEW.push(["TIMORE", "Paura con educazione"],["TONACA", "Abito religioso lungo"],["TORACE", "Gabbia che custodisce cuore e polmoni"],["TORERO", "Si veste di luce davanti al toro"]);
NEW.push(["TORNEO", "Competizione di molti incontri"],["TORNIO", "Macchina che modella girando"],["TROFEO", "Oggetto che ricorda una vittoria"],["TROMBA", "Fiato squillante e vortice d'aria"]);
NEW.push(["TROPPO", "Eccedenza in una parola"],["TRUFFA", "Inganno con tornaconto"],["TUMORE", "Crescita patologica da diagnosticare"],["TUNICA", "Veste semplice e lunga"]);
NEW.push(["TUTORE", "Sostegno, legale o ortopedico"],["UNIONE", "Somma di parti che provano a restare insieme"],["VAGONE", "Stanza mobile su rotaie"],["VALORE", "Prezzo, coraggio o numero"]);
NEW.push(["VAPORE", "Acqua diventata aria"],["VEDOVA", "Donna dopo la perdita del marito"],["VELENO", "Sostanza che nuoce gia in piccole dosi"],["VELOCE", "Rapido, ma non sempre frettoloso"]);
NEW.push(["VENERE", "Dea, pianeta e canone di bellezza"],["VERMUT", "Aperitivo aromatizzato da Torino"],["VICINO", "Prossimo nello spazio o nella casa accanto"],["VIGILE", "Sorveglia o dirige il traffico"]);
NEW.push(["VIGORE", "Forza piena e vitale"],["VIMINI", "Rami flessibili da intreccio"],["ZEFIRO", "Vento leggero d'Occidente"],["ZIGOMO", "Osso che disegna lo spigolo della guancia"]);

// ===================== 7 LETTERE (245 voci) =====================
NEW.push(["ACCENTO", "Segno che cambia suono e talvolta senso"],["AGNELLO", "Piccolo ovino e simbolo pasquale"],["ALBATRO", "Grande uccello oceanico da poesia"],["ALBERGO", "Casa temporanea con reception"]);
NEW.push(["ALCIONE", "Uccello marino e mito di bonaccia"],["ALLEGRO", "Veloce in musica, lieto nel carattere"],["ANTENNA", "Sente segnali che gli occhi ignorano"],["APIARIO", "Quartiere ordinato delle arnie"]);
NEW.push(["ARANCIO", "Albero, colore e frutto in una parola"],["ARBITRO", "Fischia perche gli altri non litighino troppo"],["ARGENTO", "Metallo secondo sul podio e primo in posate"],["ARMADIO", "Nasconde abiti e talvolta scheletri"]);
NEW.push(["ARMENIA", "Paese caucasico fra Oriente e Occidente"],["ATLANTE", "Regge il mondo nei miti e le mappe in libreria"],["AUTUNNO", "Stagione che fa cadere cio che primavera aveva promesso"],["BACHECA", "Vetrina per avvisi e trofei"]);
NEW.push(["BALCONE", "Sporgenza domestica con vista"],["BAMBINO", "Essere umano prima delle scuse adulte"],["BANDITO", "Fuori legge o annunciato pubblicamente"],["BARATTO", "Scambio prima del prezzo"]);
NEW.push(["BARBONE", "Ha riccioli da cane o strada da senzatetto"],["BARCONE", "Imbarcazione grande e spesso carica"],["BATTITO", "Ritmo del cuore o d'ali"],["BIVACCO", "Riparo provvisorio da montagna"]);
NEW.push(["BOTTEGA", "Negozio che conserva mani artigiane"],["BOTTONE", "Tiene insieme due lembi con un piccolo varco"],["BRACCIO", "Arto, leva o tratto di mare"],["BRAMITO", "Voce d'amore del cervo"]);
NEW.push(["BRIVIDO", "Freddo che corre sulla pelle"],["BUSSARE", "Chiedere ingresso con le nocche"],["BUSSOLA", "Ago che cerca il nord"],["CANTINA", "Sotterraneo dove il vino riposa"]);
NEW.push(["CAPANNA", "Rifugio povero e rurale"],["CARAFFA", "Versa acqua con eleganza semplice"],["CARCERE", "Luogo dove la liberta ha muri"],["CARDINE", "Perno che fa girare l'uscio; punto essenziale"]);
NEW.push(["CARDONE", "Ortaggio parente del carciofo"],["CAROGNA", "Corpo morto o persona spregevole"],["CARRUBA", "Frutto mediterraneo da farina dolce"],["CARTONE", "Materiale da scatole e film disegnati"]);
NEW.push(["CASCATA", "Acqua che cade con spettacolo"],["CAVALLO", "Corre, salta e negli scacchi fa una L"],["CAVERNA", "Grotta profonda da preistoria"],["CAVIALE", "Uova nere da lusso freddo"]);
NEW.push(["CEMENTO", "Pietra artificiale che lega"],["CHIMERA", "Mostro antico e desiderio irraggiungibile"],["CICOGNA", "Uccello accusato di portare neonati"],["CINGHIA", "Striscia che stringe o trasmette"]);
NEW.push(["CIPOLLA", "Bulbo che commuove il cuoco"],["CIVETTA", "Rapace notturno e richiamo da vetrina"],["CLARINO", "Fiato di legno dal suono limpido"],["COLLINA", "Rilievo che non osa diventare monte"]);
NEW.push(["COLOMBA", "Uccello pasquale e simbolo pacifico"],["COLONNA", "Sostegno architettonico e rubrica"],["CONFINE", "Linea che divide senza avere spessore"],["CORALLO", "Animale marino che sembra minerale"]);
NEW.push(["CORNICE", "Bordo che nobilita il quadro"],["CORTILE", "Spazio interno tra muri"],["COSTUME", "Abito da spiaggia o abitudine sociale"],["CRATERE", "Bocca di vulcano o coppa antica"]);
NEW.push(["CROTALO", "Serpente che avverte prima di mordere"],["CUSCINO", "Morbidezza tra capo e letto"],["DARSENA", "Specchio d'acqua riparato per barche"],["DELFINO", "Mammifero che sorride nel mare"]);
NEW.push(["DESERTO", "Luogo dove l'acqua diventa notizia"],["DIADEMA", "Corona piu da regina che da re"],["DILEMMA", "Due vie, nessuna davvero comoda"],["DIPLOMA", "Carta che certifica un percorso"]);
NEW.push(["DRAGONE", "Mostro araldico da fuoco"],["EDICOLA", "Vende giornali o custodisce santi"],["EMPORIO", "Negozio dove si trova un po' di tutto"],["ERBARIO", "Raccolta di piante pressate"]);
NEW.push(["ESPERTO", "Ne sa abbastanza da sembrare prudente"],["ETRUSCO", "Antico abitante dell'Italia centrale"],["FAGIANO", "Selvatico piumato da caccia"],["FALANGE", "Schiera compatta o osso delle dita"]);
NEW.push(["FANTINO", "Piccolo cavaliere da palio"],["FASCINO", "Attrazione che non si misura"],["FERETRO", "Contenitore dell'ultimo viaggio"],["FERMATA", "Punto in cui il mezzo concede ingresso"]);
NEW.push(["FILANDA", "Fabbrica della seta d'altri tempi"],["FINEZZA", "Sottigliezza elegante"],["FOLGORE", "Lampo che colpisce"],["FONTANA", "Architettura dell'acqua in piazza"]);
NEW.push(["FORBICE", "Taglia sempre in coppia"],["FORMICA", "Piccola lavoratrice che insegna previdenza alla cicala"],["FORTINO", "Difesa in miniatura"],["FOSSILE", "Resto che il tempo ha pietrificato"]);
NEW.push(["FRAGOLA", "Rosso dolce che matura basso"],["FRAGORE", "Rumore che riempie lo spazio"],["FRECCIA", "Messaggio appuntito dell'arco o della strada"],["FUMETTO", "Racconto disegnato che parla in nuvolette"]);
NEW.push(["GALLINA", "Fa uova, non voli memorabili"],["GALOPPO", "Andatura che scuote sella e fantino"],["GAMBERO", "Crostaceo famoso per il passo all'indietro"],["GEMELLO", "Nato insieme, non sempre identico"]);
NEW.push(["GENTILE", "Cortese o appartenente a genti non ebraiche"],["GERANIO", "Fiore da balcone resistente"],["GHIANDA", "Frutto della quercia e promessa di bosco"],["GIUNGLA", "Vegetazione dove perdersi e metafora d'ufficio"]);
NEW.push(["GLICINE", "Rampicante violaceo e profumato"],["GOBELIN", "Arazzo francese da parete nobile"],["GONDOLA", "Barca veneziana senza motore"],["GORILLA", "Primato enorme e guardia del corpo"]);
NEW.push(["GRADINO", "Passo architettonico verso l'alto"],["GRAFITE", "Carbonio che lascia tracce nella matita"],["GRIFONE", "Creatura araldica meta aquila e meta leone"],["INCANTO", "Meraviglia o vendita al miglior offerente"]);
NEW.push(["INSEGNA", "Fa riconoscere un negozio o un reparto"],["INVERNO", "Stagione di cappotti e giornate corte"],["INVIDIA", "Desiderio verde per il bene altrui"],["ISTANTE", "Tempo troppo breve per diventare storia"]);
NEW.push(["ISTRICE", "Roditore armato di aculei"],["LACRIMA", "Acqua salata dell'occhio"],["LAMPADA", "Oggetto che addomestica il buio"],["LAMPONE", "Frutto rosso da rovo elegante"]);
NEW.push(["LASAGNA", "Strati di pasta che fanno domenica"],["LAVAGNA", "Superficie nera o bianca da cancellare"],["LETARGO", "Sonno animale contro l'inverno"],["LEVANTE", "Oriente del sole e vento"]);
NEW.push(["LIBRAIO", "Mercante di pagine"],["LICHENE", "Unione tenace di fungo e alga"],["LIQUORE", "Dolce alcolico da fine pasto"],["LUCERNA", "Lampada antica da olio"]);
NEW.push(["MACELLO", "Luogo di carne e sinonimo di disordine"],["MAGNETE", "Attira senza mani"],["MALARIA", "Febbre di palude e zanzare"],["MALIZIA", "Intelligenza con doppio fondo"]);
NEW.push(["MANETTA", "Tiene i polsi o apre gas"],["MAREMMA", "Terra toscana di butteri e paludi bonificate"],["MARGINE", "Bordo del foglio e spazio di manovra"],["MATTONE", "Pezzo d'edificio e noia pesante"]);
NEW.push(["MENSOLA", "Piccola terrazza per libri e vasi"],["MERINGA", "Dolce fatto quasi d'aria e zucchero"],["METEORA", "Brilla un attimo e sparisce"],["MIDOLLO", "Parte interna dell'osso e sostanza"]);
NEW.push(["MIGNOLO", "Il piu piccolo della mano"],["MISTERO", "Quel che resiste alla spiegazione"],["MONTONE", "Maschio lanoso e colpo di testa"],["MUSCOLO", "Si contrae senza discutere"]);
NEW.push(["NARCISO", "Si specchia troppo, per mito"],["NETTARE", "Bevanda divina e succo floreale"],["OCARINA", "Piccolo fiato d'argilla"],["ODISSEA", "Viaggio lunghissimo e poema"]);
NEW.push(["OFFERTA", "Proposta, sconto o dono all'altare"],["ORACOLO", "Rispondeva oscuro per mestiere"],["ORIGANO", "Erba che sa di pizza e Mediterraneo"],["ORIGINE", "Punto da cui tutto comincia"]);
NEW.push(["OSPIZIO", "Ricovero d'altri tempi"],["PADELLA", "Contenitore basso per friggere"],["PADRONE", "Possiede, comanda o ospita"],["PALAZZO", "Edificio importante e ambiente di potere"]);
NEW.push(["PANTERA", "Felino nero nell'immaginario"],["PARANZA", "Barca da pesca e frittura di pesci piccoli"],["PASSATO", "Tempo trascorso e verdura setacciata"],["PASSERO", "Uccello urbano di piccola taglia"]);
NEW.push(["PASTORE", "Guida greggi o anime"],["PENTOLA", "Sta sul fuoco e nasconde coperchi proverbiali"],["PERTICA", "Asta lunga da salti e misure"],["PIANETA", "Corpo errante intorno a una stella"]);
NEW.push(["PICCONE", "Attrezzo che apre terra e roccia"],["PIOGGIA", "Acqua che cade senza rubinetti"],["PISELLO", "Legume in baccello e fiaba sul materasso"],["PISTOLA", "Arma corta, anche da starter"]);
NEW.push(["POLENTA", "Granturco che diventa piatto giallo"],["POLLAIO", "Casa rumorosa di galline"],["POLVERE", "Materia minuta che torna sempre"],["PORFIDO", "Pietra dura da strade e piazze"]);
NEW.push(["PORTICO", "Cammino coperto da colonne"],["PORTONE", "Ingresso piu solenne della porta"],["PRESEPE", "Scena natalizia in miniatura"],["PRIMATO", "Record o superiorita"]);
NEW.push(["PRIMULA", "Fiore che anticipa la primavera"],["PROFILO", "Contorno del volto e pagina personale"],["PROFUMO", "Presenza invisibile che resta nell'aria"],["PRONOME", "Sostituisce il nome senza farsene accorgere"]);
NEW.push(["PULCINO", "Neonato con piumino giallo"],["PULPITO", "Alto luogo da cui si predica"],["QUERCIA", "Albero da ghiande e longevita"],["RICETTA", "Formula di cucina o farmacia"]);
NEW.push(["RIFUGIO", "Riparo di montagna e di paura"],["RIMEDIO", "Soluzione pratica al malanno"],["RISOTTO", "Riso che chiede brodo e pazienza"],["RONDINE", "Uccello proverbiale di primavera"]);
NEW.push(["ROSARIO", "Preghiera contata a grani"],["RUGIADA", "Gocce del mattino senza pioggia"],["SALOTTO", "Stanza di conversazione e televisore"],["SANDALO", "Scarpa aperta o legno profumato"]);
NEW.push(["SARDINA", "Piccolo pesce da scatola e banco"],["SCALINO", "Un gradino quando si fa quotidiano"],["SCARICO", "Vuoto, stanco o tubo d'uscita"],["SCATOLA", "Contenitore che promette sorpresa"]);
NEW.push(["SCETTRO", "Bastone che comanda"],["SCHIENA", "Parte che porta pesi e tradimenti"],["SCIALLE", "Abbraccio di stoffa sulle spalle"],["SCOPPIO", "Rumore breve di esplosione"]);
NEW.push(["SCORCIO", "Vista parziale o finale di stagione"],["SCRIGNO", "Piccola cassa da segreti preziosi"],["SIGNORE", "Uomo distinto, titolo di cortesia"],["SIMBOLO", "Segno che vale piu di se stesso"]);
NEW.push(["SIPARIO", "Tela che decide quando comincia lo spettacolo"],["SOLDATO", "Pedina in divisa"],["SORELLA", "Parente dello stesso ceppo familiare"],["SORRISO", "Curva del viso che disarma"]);
NEW.push(["SOSPIRO", "Respiro che dice piu di una parola"],["SPETTRO", "Fantasma o gamma di colori"],["SPINACI", "Verdura resa famosa da un marinaio"],["SPIRALE", "Linea che gira senza chiudersi subito"]);
NEW.push(["SPIRITO", "Anima, alcol o prontezza di battuta"],["STATUTO", "Legge fondamentale di un ente"],["TALENTO", "Dote che chiede esercizio"],["TAMBURO", "Pelle tesa che parla a colpi"]);
NEW.push(["TAPPETO", "Pavimento morbido e oggetto da favola"],["TARTUFO", "Tesoro sotterraneo da fiuto"],["TEMPERA", "Colore da scuola e tecnica pittorica"],["TERMINE", "Fine, parola o scadenza"]);
NEW.push(["TERRORE", "Paura portata al massimo"],["TIRANNO", "Governa con paura, non con consenso"],["TORNADO", "Vortice che alza tetti e polvere"],["TRALCIO", "Ramo della vite"]);
NEW.push(["TRAPANO", "Fa buchi girando"],["TRIBUNA", "Posto rialzato per guardare o parlare"],["TRINCEA", "Fossa dove la guerra si ferma"],["UCCELLO", "Animale piumato: talvolta parola-tranello"]);
NEW.push(["UFFICIO", "Stanza di pratiche e scrivanie"],["URAGANO", "Tempesta con nome proprio"],["VASSOIO", "Porta bicchieri senza bere"],["VEDETTA", "Sorveglia da lontano"]);
NEW.push(["VELIERO", "Nave che obbedisce al vento"],["VELLUTO", "Stoffa che invita la mano"],["VERBENA", "Pianta odorosa da giardino e infusi"],["VESCOVO", "Pastore di diocesi e pezzo degli scacchi"]);
NEW.push(["VESUVIO", "Vulcano che domina Napoli"],["VETRINA", "Mostra merce senza venderla ancora"],["VIAGGIO", "Movimento nello spazio e nella mente"],["VIBRATO", "Oscillazione espressiva del suono"]);
NEW.push(["VIGNETO", "Vigna organizzata in filari"],["VIOLINO", "Quattro corde sotto l'archetto"],["VORTICE", "Giro che risucchia"],["VULCANO", "Montagna che respira fuoco"]);
NEW.push(["ZAFFIRO", "Gemma blu da anelli e corone"],["ZATTERA", "Imbarcazione minima e provvisoria"],["ZENZERO", "Radice piccante da tisana e cucina"],["ZOCCOLO", "Calzatura di legno, base o unghia"]);
NEW.push(["ZODIACO", "Cerchio di segni per astrologi"]);

// ===================== 8 LETTERE (172 voci) =====================
NEW.push(["ACQUARIO", "Vasca domestica o segno d'aria che porta acqua"],["AFFRESCO", "Pittura che nasce sull'intonaco umido"],["ALABARDA", "Arma in asta da guardie solenni"],["ALLODOLA", "Uccello mattiniero che canta in alto"]);
NEW.push(["ALTALENA", "Gioco che vive di salite e discese"],["AMBIENTE", "Cio che circonda e condiziona"],["ANGUILLA", "Pesce-serpente da acque dolci e misteri"],["ANTILOPE", "Erbivoro veloce da savana"]);
NEW.push(["ARCHIVIO", "Memoria ordinata di carte e file"],["ARMATURA", "Difesa metallica che rende lento il cavaliere"],["ARTIGLIO", "Unghia d'offesa dei rapaci"],["ASPARAGO", "Turione verde da primavera"]);
NEW.push(["ASTUCCIO", "Piccolo custode di penne"],["BAGAGLIO", "Peso che il viaggiatore dichiara o nasconde"],["BANDIERA", "Identita che sventola"],["BASILICA", "Chiesa grande e forma romana antica"]);
NEW.push(["BASILICO", "Foglia ligure per eccellenza"],["BISACCIA", "Doppia sacca da viaggio povero"],["BISCOTTO", "Secco, dolce e pronto all'inzuppo"],["BRACIERE", "Contiene fuoco senza camino"]);
NEW.push(["BRIGANTE", "Fuorilegge da montagne e leggende"],["BRINDISI", "Citta pugliese o gesto coi calici"],["CALAMARO", "Mollusco che sa d'inchiostro"],["CALAMITA", "Attira ferro e curiosita"]);
NEW.push(["CAMOSCIO", "Agile montanaro con corna"],["CAMPIONE", "Vincitore, esemplare o assaggio"],["CANTANTE", "Usa la voce come mestiere"],["CANTIERE", "Luogo dove l'incompiuto e normale"]);
NEW.push(["CAPRIOLO", "Salto elegante o piccolo cervide"],["CARABINA", "Arma lunga piu precisa che rumorosa"],["CAROVANA", "Fila lenta da piste e deserti"],["CARRELLO", "Porta spesa, bagagli o attrezzi"]);
NEW.push(["CASTAGNA", "Frutto in riccio e colpo d'errore"],["CASTELLO", "Dimora fortificata e incastro di carte"],["CENTAURO", "Creatura doppia: busto umano e corpo equino"],["CERNIERA", "Unisce aprendo e chiudendo"]);
NEW.push(["CERVELLO", "Materia che pensa se stessa"],["CETRIOLO", "Ortaggio allungato da insalata"],["CICERONE", "Guida che spiega troppo bene"],["CILINDRO", "Solido, cappello o parte del motore"]);
NEW.push(["CISTERNA", "Grande recipiente d'acqua nascosta"],["CLAUSOLA", "Piccolo patto dentro un contratto"],["COCOMERO", "Estate rossa sotto buccia verde"],["COLOSSEO", "Anfiteatro che Roma porta come simbolo"]);
NEW.push(["CONIGLIO", "Animale pauroso e prolifico"],["CONTESSA", "Nobile al femminile"],["CORNETTA", "Ricevitore telefonico e brioche regionale"],["CROSTATA", "Dolce a griglia di pasta"]);
NEW.push(["CUCCIOLO", "Piccolo che addolcisce il nome dell'animale"],["DENTISTA", "Professionista che fa aprire la bocca"],["DIAMANTE", "Pietra durissima e campo da baseball"],["DIAPASON", "Da il la senza cantare"]);
NEW.push(["DINASTIA", "Famiglia che eredita il potere"],["ELASTICO", "Torna indietro quando lo tiri"],["ELEFANTE", "Pachiderma dalla memoria proverbiale"],["EMISFERO", "Meta di globo o di cervello"]);
NEW.push(["EPIGRAFE", "Parole incise per durare"],["ESERCITO", "Forza armata di terra"],["ESTUARIO", "Foce larga dove il fiume incontra il mare"],["EVASIONE", "Fuga o distrazione fiscale"]);
NEW.push(["FANTASMA", "Presenza che appare mancando"],["FARFALLA", "Insetto e stile di nuoto"],["FATTORIA", "Casa di campagna con produzione"],["FELICITA", "Pienezza che spesso dura poco"]);
NEW.push(["FENDENTE", "Colpo di lama dall'alto"],["FENOMENO", "Fatto osservabile o persona eccezionale"],["FERROVIA", "Strada di rotaie"],["FINESTRA", "Taglio nel muro da cui entra luce"]);
NEW.push(["FOCACCIA", "Pane basso che profuma di olio"],["FRASSINO", "Albero da manici e boschi"],["FRATELLO", "Maschio nato dagli stessi genitori"],["FRONTONE", "Triangolo di tempio sopra colonne"]);
NEW.push(["GABBIANO", "Bianco frequentatore di porti"],["GALASSIA", "Citta di stelle"],["GALLERIA", "Strada sotto monte o sala d'arte"],["GAROFANO", "Fiore da occhiello e garibaldini"]);
NEW.push(["GAZZELLA", "Antilope leggera e pattuglia veloce"],["GHIACCIO", "Acqua irrigidita dal freddo"],["GIARDINO", "Spazio dove la natura e addomesticata"],["GIORNALE", "Carta quotidiana, sempre meno quotidiana"]);
NEW.push(["GIRASOLE", "Fiore che sembra inseguire il giorno"],["GRANDINE", "Ghiaccio che cade a chicchi"],["GRANELLO", "Minima parte di sabbia, sale o dubbio"],["INCUDINE", "Resiste ai colpi del fabbro"]);
NEW.push(["INDOVINO", "Risponde prima che accada"],["INFANZIA", "Eta in cui tutto sembra piu grande"],["LAMPIONE", "Albero di luce stradale"],["LEOPARDO", "Felino maculato da savana e foresta"]);
NEW.push(["LEVRIERO", "Cane fatto per correre"],["LIBECCIO", "Vento di sud-ovest, spesso umido"],["MACCHINA", "Dispositivo, automobile o complotto"],["MAIALINO", "Piccolo suino da fiaba o fattoria"]);
NEW.push(["MANDORLA", "Seme dolce dentro guscio duro"],["MANTELLO", "Copre spalle, animali e supereroi"],["MARMOTTA", "Dormigliona delle Alpi"],["MARTELLO", "Colpisce chiodi e incudini"]);
NEW.push(["MASCHERA", "Nasconde il volto o lo interpreta"],["MEDAGLIA", "Metallo che ricorda merito"],["MERLUZZO", "Pesce che da anche baccala"],["METAFORA", "Trasferisce senso senza traslocare"]);
NEW.push(["MINESTRA", "Piatto caldo da cucchiaio"],["MIRAGGIO", "Inganno d'acqua nel caldo"],["MONTAGNA", "Rilievo che costringe a salire"],["MUGHETTO", "Campanellini bianchi profumati"]);
NEW.push(["NASTRINO", "Piccola striscia da pacco o uniforme"],["NAUFRAGO", "Sopravvissuto che il mare ha respinto"],["NEVICATA", "Caduta bianca che zittisce le strade"],["NOCCIOLO", "Albero e parte dura della questione"]);
NEW.push(["NOSTROMO", "Marinaio d'autorita sul ponte"],["NOTTURNO", "Vive o suona quando il giorno tace"],["OCCHIALE", "Aiuta la vista senza essere occhio"],["OFFICINA", "Luogo dove il guasto diventa lavoro"]);
NEW.push(["OMBRELLO", "Piccolo tetto portatile"],["OPIFICIO", "Stabilimento produttivo in parola antica"],["ORCHIDEA", "Fiore elegante dai nomi esotici"],["ORTOLANO", "Coltiva verdure piu che fiori"]);
NEW.push(["OSPEDALE", "Citta dei malati e dei turni"],["PAGLIAIO", "Montagna rustica dove cercare aghi proverbiali"],["PANCETTA", "Maiale in strati, amato dalla carbonara"],["PANCHINA", "Sedile pubblico e destino delle riserve"]);
NEW.push(["PARABOLA", "Racconto esemplare e curva matematica"],["PENSIERO", "Cosa invisibile che pesa"],["PIANISTA", "Interprete che usa dieci dita e molti tasti"],["PILASTRO", "Sostegno materiale o morale"]);
NEW.push(["PINGUINO", "Uccello in frac che non vola"],["PIRAMIDE", "Solido e tomba faraonica"],["POLTRONA", "Sedia comoda e incarico ambito"],["PRESEPIO", "Nativita in scala domestica"]);
NEW.push(["QUADERNO", "Pagine legate per appunti e compiti"],["RAPSODIA", "Composizione libera e appassionata"],["RELIQUIA", "Resto sacro custodito"],["RETICOLO", "Rete di linee o di nervi"]);
NEW.push(["RIFLESSO", "Immagine di ritorno o reazione rapida"],["RIGATONE", "Pasta che trattiene il sugo"],["RUSCELLO", "Acqua piccola ma in cammino"],["SARACENO", "Arabo medievale nelle cronache cristiane"]);
NEW.push(["SARGASSO", "Mare famoso per alghe galleggianti"],["SCANDALO", "Rumore morale e pubblico"],["SCARABEO", "Coleottero sacro e gioco di lettere"],["SCARPONE", "Calzatura che non teme sentieri"]);
NEW.push(["SCIROPPO", "Dolce rimedio da cucchiaio"],["SCULTURA", "Arte che toglie o aggiunge materia"],["SEGGIOLA", "Sedia con nome familiare"],["SENTIERO", "Strada stretta che non vuole asfalto"]);
NEW.push(["SEPOLCRO", "Tomba con tono solenne"],["SERENATA", "Canto sotto una finestra, almeno in teoria"],["SERPENTE", "Animale senza zampe che cambia pelle"],["SMERALDO", "Verde prezioso da gioielleria"]);
NEW.push(["SOFFITTO", "Cielo domestico"],["SORGENTE", "Punto da cui l'acqua comincia"],["SPAVENTO", "Paura che arriva di colpo"],["SPIAGGIA", "Confine sabbioso fra terra e mare"]);
NEW.push(["STECCATO", "Recinto di legno o divisione ideale"],["TACCHINO", "Volatile natalizio e tripletta nel bowling"],["TASTIERA", "File di tasti per musica o lettere"],["TELAMONE", "Figura maschile che regge l'architettura"]);
NEW.push(["TELEFONO", "Voce a distanza, anche senza filo"],["TEMPESTA", "Disordine violento del cielo e del mare"],["TENAGLIA", "Strumento che afferra con due becchi"],["TERRAZZA", "Esterno domestico sopra il suolo"]);
NEW.push(["TRAMONTO", "Momento in cui il giorno si spegne"],["TRAPEZIO", "Figura geometrica e attrezzo da acrobati"],["TRATTORE", "Motore lento che lavora la terra"],["TRIDENTE", "Forcone a tre punte di Nettuno"]);
NEW.push(["TROMBONE", "Ottone che scorre per cambiare nota"],["UNICORNO", "Cavallo impossibile con un solo corno"],["USIGNOLO", "Cantore notturno dei poeti"],["VASCELLO", "Nave antica da romanzi di mare"]);
NEW.push(["VENDETTA", "Giustizia privata, spesso peggiore del torto"],["ZABAIONE", "Crema di uova, zucchero e vino"],["ZAMPILLO", "Acqua che sale per cadere"],["ZUCCHINA", "Ortaggio verde, femminile del diminutivo"]);

// ===================== 9 LETTERE (57 voci) =====================
NEW.push(["AEROPORTO", "Citta delle partenze e degli arrivi"],["ASTERISCO", "Stellina che rimanda in nota"],["ATLANTICO", "Oceano fra vecchio e nuovo mondo"],["BABILONIA", "Citta di torri, esili e confusione"]);
NEW.push(["BALLERINA", "Sta sulle punte per mestiere"],["BELVEDERE", "Luogo fatto per guardare bene"],["BERSAGLIO", "Punto che attira frecce e colpi"],["BOSCHETTO", "Piccolo bosco quasi domestico"]);
NEW.push(["CAVALIERE", "Titolo, ordine o combattente a cavallo"],["CERBIATTO", "Giovane cervo da occhi grandi"],["CERIMONIA", "Forma solenne data agli eventi"],["CINGHIALE", "Selvatico con zanne e setole"]);
NEW.push(["COMIGNOLO", "Piccola uscita del fumo sul tetto"],["CREPACCIO", "Ferita profonda nel ghiaccio"],["CRISALIDE", "Attesa immobile prima delle ali"],["CRISTALLO", "Vetro nobile e struttura ordinata"]);
NEW.push(["ECLETTICO", "Sceglie da piu stili senza fissarsi"],["FORMAGGIO", "Latte diventato forma e stagionatura"],["GIACIGLIO", "Letto povero, spesso improvvisato"],["GRANCASSA", "Tamburo grande e propaganda esagerata"]);
NEW.push(["IPPOCAMPO", "Cavalluccio marino e parte del cervello"],["IPPOGRIFO", "Creatura fantastica da poema cavalleresco"],["LABIRINTO", "Strada che si moltiplica per confondere"],["LATITANTE", "Assente per sfuggire alla legge"]);
NEW.push(["LIBELLULA", "Insetto volante che sembra un piccolo elicottero"],["LUCIGNOLO", "Stoppino e cattivo compagno di Pinocchio"],["MADRIGALE", "Componimento poetico e musicale antico"],["MAESTRALE", "Vento di nord-ovest e guida marinaresca"]);
NEW.push(["MANDARINO", "Agrume, lingua e funzionario imperiale"],["MELAGRANA", "Frutto dai molti semi rubini"],["MERIDIANA", "Orologio che chiede il sole"],["ORECCHINO", "Gioiello sospeso al lobo"]);
NEW.push(["ORIZZONTE", "Linea irraggiungibile dello sguardo"],["ORNAMENTO", "Aggiunta che abbellisce senza reggere"],["PALAFITTA", "Casa sollevata sull'acqua"],["PARADOSSO", "Verita travestita da assurdo"]);
NEW.push(["PELLICCIA", "Abito caldo e questione etica"],["PROVINCIA", "Territorio intermedio fra comune e regione"],["RAGANELLA", "Piccola rana o strumento rumoroso"],["RAGNATELA", "Opera geometrica del ragno"]);
NEW.push(["RAVANELLO", "Radice rossa dal morso piccante"],["RICCHEZZA", "Abbondanza che non e solo denaro"],["SALMERINO", "Pesce d'acqua fredda da torrente"],["SCALPELLO", "Lama dello scultore e del chirurgo"]);
NEW.push(["SCORPIONE", "Artropode con coda armata e segno zodiacale"],["SOLITARIO", "Solo, o gioco con carte e pazienza"],["SPLENDORE", "Luce portata al massimo"],["STAMBECCO", "Capra alpina da corna arcuate"]);
NEW.push(["STRUMENTO", "Mezzo per fare o far musica"],["TALISMANO", "Oggetto che promette fortuna"],["TARANTOLA", "Ragno peloso da paure e pizzica"],["TARTARUGA", "Lenta corazza vivente"]);
NEW.push(["TERRICCIO", "Terra pronta per vasi e semi"],["TRAGHETTO", "Nave breve fra due rive"],["TRIANGOLO", "Tre lati bastano a chiuderlo"],["VENTAGLIO", "Apre e muove aria a mano"]);
NEW.push(["VIANDANTE", "Camminatore da strade antiche"]);

// ===================== 10 LETTERE (15 voci) =====================
NEW.push(["CAVALLETTA", "Insetto saltatore e sostegno da pittore"],["CITTADELLA", "Fortezza dentro o accanto alla citta"],["COCCINELLA", "Coleottero rosso portafortuna"],["DROMEDARIO", "Ha una gobba e molta pazienza desertica"]);
NEW.push(["ELICOTTERO", "Velivolo che si solleva girando"],["FRINGUELLO", "Uccello minuto dei fringillidi"],["GONDOLIERE", "Conduce senza motore nei canali veneziani"],["INCHIOSTRO", "Liquido che rende visibili le parole"]);
NEW.push(["LENTICCHIA", "Piccolo legume portafortuna"],["LOCOMOTIVA", "Tira il convoglio stando davanti"],["PERDIZIONE", "Rovina morale o amore fatale"],["SALAMANDRA", "Anfibio legato per mito al fuoco"]);
NEW.push(["SCOIATTOLO", "Roditore arboricolo che fa scorte"],["SINGHIOZZO", "Interruzione ritmica del respiro"],["TAMBURELLO", "Piccolo tamburo e sport da piazza"]);

// ===================== 11 LETTERE (4 voci) =====================
NEW.push(["COCCODRILLO", "Rettilone da lacrime proverbiali"],["FENICOTTERO", "Uccello rosa su zampe sottili"],["MONGOLFIERA", "Pallone che sale scaldando aria"],["PUNGIGLIONE", "Ago naturale di chi punge"]);

module.exports = NEW;
