// Nuove voci per il DB cruciverba. Stile Settimana Enigmistica:
// caselle corte = sigle, targhe, note, simboli; abbondanza di parole 2-5 lettere.
const NEW = [];

// ===================== 2 LETTERE =====================
NEW.push(
  ["TO","Torino sulle targhe"],["RM","Roma sulle vecchie targhe"],
  ["BO","Bologna automobilistica"],["GE","Genova sulle targhe"],
  ["PA","Palermo in sigla"],["BA","Bari sulle targhe"],
  ["CA","Cagliari automobilistica"],["AT","Asti sulle targhe"],
  ["AL","Alessandria in sigla"],["CO","Como sulle targhe"],
  ["PI","Pisa automobilistica"],["VR","Verona sulle targhe"],
  ["PD","Padova in sigla"],["TS","Trieste sulle targhe"],
  ["SO","Sondrio automobilistica"],["FA","La nota dopo il mi"],
  ["SI","La settima nota"],["IO","Il pronome di chi parla"],
  ["TU","Il pronome dell'amico"],["NE","Particella pronominale"],
  ["PO","Il maggior fiume italiano"],["SU","Il contrario di giu"],
  ["FE","Il ferro del chimico"],["CU","Il rame degli elementi"],
  ["AU","Simbolo chimico dell'oro"],["TV","La si guarda in salotto"],
  ["CD","Disco audio in sigla"],["GO","Gioco da tavolo orientale"],
  ["BR","Brindisi sulle targhe"],["UE","L'Unione dei 27, in sigla"]
);

// ===================== 3 LETTERE =====================
NEW.push(
  ["ALI","Le ha l'aereo"],["AMO","Lo abbocca il pesce"],["AVO","Antenato, nonno"],
  ["BAR","Ci si beve il caffe"],["BIS","Richiesta a teatro"],["BOA","Grosso serpente che stritola"],
  ["BUE","Rumina nella stalla"],["DEA","Divinita femminile"],["DEI","Gli abitanti dell'Olimpo"],
  ["DIO","L'Onnipotente"],["DUE","Il numero della coppia"],["ECO","Rimbalza tra i monti"],
  ["EGO","L'io secondo Freud"],["EMU","Grosso uccello australiano"],["ENI","Colosso energetico italiano"],
  ["ESA","L'agenzia spaziale europea"],["FAN","Tifoso entusiasta"],["FEZ","Copricapo con nappa"],
  ["FIO","Pagare il... per una colpa"],["GAS","Esce dai fornelli"],["GEL","Fissa i capelli"],
  ["GRU","Uccello dal lungo collo"],["IVA","Imposta sui consumi"],["KIT","Set di montaggio"],
  ["LEI","Pronome di cortesia"],["LUI","Pronome maschile"],["MAI","In nessun tempo"],
  ["NOI","Pronome di prima plurale"],["ODE","Poesia lirica solenne"],["OHM","Unita di resistenza elettrica"],
  ["ORO","Metallo dei lingotti"],["PIO","Devoto e religioso"],["RAI","La tv di Stato"],
  ["REO","Il colpevole, per il giudice"],["ROC","Uccello gigante delle leggende"],["SUD","Punto cardinale caldo"],
  ["SET","Una partita del tennis"],["TAO","Principio del taoismo"],["TRE","Numero dispari dopo il due"],
  ["UFO","Oggetto volante misterioso"],["UNO","Il primo dei numeri"],["USO","Consuetudine, abitudine"],
  ["ZEN","Buddismo giapponese"],["ZIA","Sorella del genitore"],["ZOO","Parco con animali esotici"],
  ["AVE","Saluto dell'antica Roma"],["CIA","Servizi segreti americani"],["DAI","Forza, coraggio!"],
  ["FBI","Polizia federale USA"],["NON","Avverbio di negazione"],["ONU","Il Palazzo di Vetro la ospita"],
  ["PER","Preposizione della moltiplicazione"],["PIU","Il segno dell'addizione"],["POI","In un secondo momento"],
  ["QUA","In questo luogo"],["RAP","Genere musicale ritmato e parlato"],["RUM","Liquore dei pirati"],
  ["TAC","Esame radiologico, in sigla"],["TIR","Grosso camion da trasporto"],["TRA","Preposizione, in mezzo"],
  ["WEB","La rete internet"],["YEN","Moneta del Giappone"],["ZAR","Imperatore russo d'altri tempi"],
  ["VAN","Furgoncino per il trasporto"],["URL","Indirizzo di un sito web"],["NEO","Piccola macchia cutanea"],
  ["TEO","...rema: dimostrazione (parte)"],["ALE","...gria: gioia (parte)"],["OSA","Chi non risica non..."],
  ["APO","..strofo: segno tipografico (parte)"],["ICO","..na: immagine sacra (parte)"],["EMO","..globina del sangue (parte)"],
  ["SOL","La nota dopo il fa"],["MEA","..culpa: ammissione (lat.)"],["RES","Cosa, in latino"],
  ["AIA","Lo spiazzo della fattoria"],["BEA","Rende felici (verbo)"],["DUO","Coppia di musicisti"],
  ["FIE","..vole, debole (parte)"],["NEA","..politano: di Napoli (parte)"],["OVA","Le uova dei pesci"],
  ["REA","Colpevole, al femminile"],["TEA","Una varieta di rosa"],["VIE","Le strade, al plurale"],
  ["ASE","..ttico, sterile (parte)"],["IDE","..ale, perfetto (parte)"],["UDO","Sento (verbo udire)"]
);

// ===================== 4 LETTERE (parte 1) =====================
NEW.push(
  ["ALBA","Il sorgere del sole"],["ALCE","Cervo nordico dalle grandi corna"],["ALGA","Pianta del mare"],
  ["ANCA","Articolazione del fianco"],["ANNO","Dura dodici mesi"],["ARCO","Scocca le frecce"],
  ["ARIA","Si respira"],["ARMA","Spada o fucile"],["ARSO","Bruciato dal fuoco"],
  ["ASIA","Il continente piu vasto"],["ASSO","Vale piu del re nelle carte"],["ATTO","Parte di una commedia"],
  ["AUTO","La si guida"],["BACO","La larva della seta"],["BARA","Accoglie il defunto"],
  ["BASE","Il fondamento di tutto"],["BENE","Il contrario di male"],["BILE","Liquido amaro del fegato"],
  ["BOIA","L'antico esecutore"],["BORA","Vento freddo di Trieste"],["BRIO","Vivacita allegra"],
  ["BUIO","Assenza di luce"],["CALO","Diminuzione, ribasso"],["CANE","Il migliore amico dell'uomo"],
  ["CAPO","Chi comanda l'ufficio"],["CARO","Costoso oppure amato"],["CASA","La nostra dimora"],
  ["CASO","Combinazione fortuita"],["CAVO","Vuoto dentro / filo elettrico"],["CECI","Legumi da hummus"],
  ["CENA","Il pasto serale"],["CERA","Quella delle api / dei lumini"],["CIAO","Saluto informale"],
  ["CIBO","Si mette in tavola"],["CIMA","La vetta del monte"],["CINA","Il paese del dragone"],
  ["COLA","Filtra il brodo"],["CONO","Quello del gelato"],["CORO","Cantano insieme"],
  ["COSA","Oggetto qualsiasi"],["COVO","Tana del bandito"],["CUBO","Solido a sei facce"],
  ["DADO","Si lancia col gioco dell'oca"],["DAMA","Gioco con le pedine"],["DARE","Il contrario di avere"],
  ["DATA","Giorno, mese e anno"],["DIVO","Star del cinema"],["DOGE","L'antico capo di Venezia"],
  ["DOPO","In seguito"],["DOSE","La quantita di medicina"],["DOTE","La qualita di una persona"],
  ["DUCA","Titolo nobiliare"],["DUNA","Collina di sabbia"],["DURO","Non cede sotto pressione"],
  ["EDEN","Il paradiso terrestre"],["EMIR","Principe arabo"],["ENTE","Organismo pubblico"],
  ["ERBA","Verde sul prato"],["EROE","Protagonista coraggioso"],["ESCA","Attira il pesce"],
  ["ETNA","Vulcano siciliano"],["EURO","La nostra moneta"],["FAMA","La celebrita"],
  ["FARE","Agire, operare"],["FARO","Guida le navi di notte"],["FASE","Tappa di un processo"],
  ["FATA","Creatura magica con la bacchetta"],["FATO","Il destino segnato"],["FAVA","Legume primaverile"],
  ["FEDE","L'anello nuziale / la fiducia"],["FETO","Il nascituro nel grembo"],["FICO","Frutto dolce estivo"],
  ["FIDO","Cane fedele per antonomasia"],["FILA","Coda di persone"],["FILO","Per cucire"],
  ["FINE","Il termine, la conclusione"],["FOCA","Mammifero dei mari freddi"],["FOTO","Scatto fotografico"],
  ["FUGA","Evasione precipitosa"],["FUMO","Esce dal camino"],["FUNE","Robusta corda"],
  ["FUSO","Per filare la lana"],["GALA","Serata di gala"],["GARA","Competizione sportiva"],
  ["GELO","Freddo intenso"],["GENE","Unita dell'eredita"],["GIRO","Il... d'Italia in bici"],
  ["GITA","Breve viaggio di piacere"],["GOAL","La rete nel calcio"],["GOLA","Il collo internamente"],
  ["GOLF","Sport con buche e mazze"],["GONG","Suona la fine del round"],["GUAI","Brutti pasticci"],
  ["GUFO","Rapace notturno"],["GURU","Maestro spirituale"],["IBIS","Uccello sacro agli egizi"],
  ["IDEA","Lampo di genio"],["ILEO","Tratto dell'intestino tenue"],["INCA","Antico popolo del Peru"],
  ["IRAN","Stato del Medio Oriente"],["IRTO","Pieno di spine"],["ITER","Il percorso burocratico"],
  ["IUTA","Fibra per i sacchi"],["JEEP","Fuoristrada robusto"],["JUDO","Arte marziale giapponese"]
);

// ===================== 4 LETTERE (parte 2) =====================
NEW.push(
  ["KAKI","Frutto arancione autunnale"],["KIWI","Frutto verde e peloso"],["LAGO","Specchio d'acqua dolce"],
  ["LAMA","Il filo del coltello"],["LANA","La da la pecora"],["LATO","Ciascun bordo del quadrato"],
  ["LAVA","Fuoriesce dal vulcano"],["LEGA","Unione tra Stati o squadre"],["LIDO","Spiaggia attrezzata"],
  ["LINO","Tessuto fresco estivo"],["LIRA","La vecchia moneta italiana"],["LITE","Aspro litigio"],
  ["LOBO","Parte dell'orecchio"],["LODE","Il massimo dei voti"],["LOGO","Il marchio aziendale"],
  ["LORO","Pronome di terza plurale"],["LUCE","Illumina la stanza"],["LUME","Vecchia lampada a olio"],
  ["LUPO","Ulula alla luna"],["MAGO","Fa giochi di prestigio"],["MALE","Il contrario di bene"],
  ["MANO","Ha cinque dita"],["MELA","Frutto di Newton"],["MENO","Il segno della sottrazione"],
  ["MENU","La lista dei piatti"],["META","Il traguardo da raggiungere"],["MICA","Affatto, per niente"],
  ["MIMO","Recita senza parlare"],["MINA","Carica esplosiva nascosta"],["MIRA","Si prende col fucile"],
  ["MITO","Antica leggenda"],["MODA","Tendenza del momento"],["MODO","La maniera di fare"],
  ["MOLO","Per l'ormeggio delle barche"],["MORA","Frutto del rovo"],["MORO","Bruno di carnagione"],
  ["MOTO","La due ruote a motore"],["MULO","Incrocio tra asino e cavalla"],["MURO","Divide due stanze"],
  ["MUSA","Ispira il poeta"],["MUTO","Non parla"],["NANO","Piccolissimo di statura"],
  ["NASO","Sente gli odori"],["NAVE","Solca i mari"],["NERO","Il colore del carbone"],
  ["NIDO","La casa degli uccellini"],["NOCE","Frutto secco a guscio duro"],["NODO","Si fa con la corda"],
  ["NOIA","Tedio, monotonia"],["NOME","Lo si scrive sul documento"],["NORD","Punto cardinale freddo"],
  ["NOTA","Annotazione a margine"],["NOVE","Il numero prima del dieci"],["NUCA","Dietro la testa"],
  ["NUDO","Senza vestiti"],["OASI","Verde nel deserto"],["OBOE","Strumento a fiato dell'orchestra"],
  ["OCRA","Colore giallo-bruno"],["ODIO","Sentimento opposto all'amore"],["OLMO","Albero ombroso"],
  ["ONDA","Si infrange sulla spiaggia"],["ORDA","Folla tumultuosa"],["ORLO","Il bordo del vestito"],
  ["ORTO","Vi crescono le verdure"],["OSSO","Lo rosicchia il cane"],["OSTE","Gestisce l'osteria"],
  ["OTTO","Il numero del polpo"],["PACE","Il contrario della guerra"],["PAGA","Lo stipendio"],
  ["PALA","Quella del fornaio o dell'eolico"],["PALO","Sostiene la rete del campo"],["PANE","Si fa con la farina"],
  ["PAPA","Il vescovo di Roma"],["PARI","Numero divisibile per due"],["PELO","Copre il gatto"],
  ["PENA","Punizione per il reo"],["PEPE","Spezia che pizzica"],["PERA","Frutto dolce a campana"],
  ["PERO","Albero della pera"],["PESO","Si misura sulla bilancia"],["POCO","Una piccola quantita"],
  ["POLO","Sport a cavallo / capo d'abbigliamento"],["POMO","La mela, poeticamente"],["POSA","Posizione per la foto"],
  ["PUMA","Felino delle Americhe"],["PUPA","Bambola, ragazza"],["PURO","Senza impurita"],
  ["QUIZ","Gioco a domande"],["RAGU","Sugo di carne"],["RAID","Incursione improvvisa"],
  ["RAMO","Si dirama dal tronco"],["RAPA","Ortaggio bianco e viola"],["RARO","Difficile da trovare"],
  ["RASO","Tessuto lucido e liscio"],["RATA","Pagamento periodico"],["RENA","La sabbia del lido"],
  ["RENE","Filtra il sangue"],["RIGA","Linea dritta sul foglio"],["RIMA","Fine di versi che suonano uguali"],
  ["RISO","Cereale dei risotti / la risata"],["RITO","Cerimonia solenne"],["ROBA","Insieme di cose"],
  ["ROCK","Genere musicale con la chitarra"],["ROGO","Grande falo"],["ROMA","La Citta Eterna"],
  ["ROSA","Fiore con le spine"],["RUDE","Rozzo e brusco"],["RUGA","Solco del viso"],
  ["RUNA","Antico segno nordico"],["SAGA","Lunga storia di famiglia"],["SALA","Stanza ampia"],
  ["SALE","Condisce e conserva"],["SANO","In buona salute"],["SCIA","La lascia la barca"],
  ["SEDE","La sede centrale"],["SEGA","Taglia il legno"],["SEME","Da cui nasce la pianta"],
  ["SENO","Funzione trigonometrica"],["SERA","Scende dopo il tramonto"],["SETA","Tessuto pregiato e lucente"],
  ["SETE","Voglia di bere"],["SILO","Deposito per il grano"],["SITO","Pagina su internet"],
  ["SODA","L'acqua... frizzante"],["SOFA","Comodo divano"],["SOLO","Senza compagnia"],
  ["SUMO","Lotta giapponese tra giganti"],["TABU","Argomento proibito"],["TALE","Quel tal individuo"],
  ["TANA","Il rifugio dell'animale"],["TARA","Il peso dell'imballaggio"],["TELA","Il pittore vi dipinge"],
  ["TEMA","Argomento del compito"],["TIMO","Erba aromatica"],["TINO","Recipiente per il vino"],
  ["TIRO","Lancio verso il bersaglio"],["TOGA","La veste dell'avvocato"],["TONO","Sfumatura di colore o voce"],
  ["TOPO","Roditore inseguito dal gatto"],["TORO","Segno zodiacale di aprile"],["TRAM","Va su rotaie in citta"],
  ["TRIO","Gruppo di tre musicisti"],["TUBA","Cappello a cilindro / ottone"],["TUBO","Conduttura cilindrica"],
  ["TUFO","Roccia vulcanica porosa"],["TUTA","Abito comodo da ginnastica"],["UNNO","Il popolo di Attila"],
  ["UOVO","Lo depone la gallina"],["URBE","La citta, in latino"],["URNA","Si vota infilando la scheda"],
  ["URTO","Brusca collisione"],["VAGO","Indefinito, impreciso"],["VANO","Inutile / stanza"],
  ["VARO","Battesimo della nave"],["VASO","Contiene i fiori"],["VATE","Poeta solenne"],
  ["VELA","Spinge la barca col vento"],["VELO","Copre il viso della sposa"],["VENA","Porta il sangue al cuore"],
  ["VERO","Conforme alla realta"],["VETO","Il diritto di opporsi"],["VILE","Vigliacco e codardo"],
  ["VINO","Si ricava dall'uva"],["VISO","Il volto"],["VITA","Il dono piu prezioso"],
  ["VITE","La pianta dell'uva / fissa col cacciavite"],["VIVO","Pieno di vita"],["VOCE","Esce dalle corde vocali"],
  ["VOLO","Tragitto in aereo"],["VOTO","Si esprime alle elezioni"],["ZERO","Nulla assoluto"],
  ["ZONA","Area, settore"],["ZELO","Diligenza scrupolosa"],["LODI","Citta della Lombardia"]
);

// ===================== 5 LETTERE (parte 1) =====================
NEW.push(
  ["ACIDO","Sapore del limone"],["ACUTO","Angolo minore di 90 gradi"],["AEREO","Vola con i passeggeri"],
  ["AGAVE","Pianta grassa da tequila"],["AGILE","Scattante e flessibile"],["ALATO","Provvisto di ali"],
  ["ALBUM","Raccolta di foto o canzoni"],["ALTRO","Diverso da questo"],["AMARO","Sapore del caffe senza zucchero"],
  ["AMENO","Piacevole e ridente"],["AMICO","Compagno fidato"],["AMORE","Sentimento tra innamorati"],
  ["ANICE","Aroma del liquore trasparente"],["ANIMA","Lo spirito dell'uomo"],["ANIMO","Coraggio, animo!"],
  ["ANTRO","Caverna oscura"],["APICE","Il punto piu alto"],["ARENA","Anfiteatro romano"],
  ["AROMA","Profumo gradevole del cibo"],["ARPIA","Mostro mitologico alato"],["ASCIA","Spacca la legna"],
  ["ASILO","Scuola dei piccolissimi"],["ASOLA","Buco per il bottone"],["ASPRO","Aspro e pungente"],
  ["ASSAI","Molto, parecchio"],["ASTRO","Corpo celeste"],["ATOMO","La piu piccola parte"],
  ["ATRIO","Ingresso del palazzo"],["AVARO","Tiene stretti i soldi"],["AVENA","Cereale del porridge"],
  ["AZOTO","Gas dell'aria, simbolo N"],["BACCA","Piccolo frutto del bosco"],["BAGNO","La stanza con la vasca"],
  ["BALLO","Si fa a ritmo di musica"],["BANCO","Quello di scuola"],["BARCA","Galleggia sull'acqua"],
  ["BASCO","Copricapo piatto"],["BEATO","Felice e sereno"],["BELLO","Gradevole alla vista"],
  ["BENDA","Fascia la ferita"],["BIRRA","Bevanda con la schiuma"],["BOMBA","Ordigno esplosivo"],
  ["BORSA","Vi si mette il portafoglio"],["BOSCO","Fitto di alberi"],["BOTTE","Contiene il vino"],
  ["BRACE","Le braci del barbecue"],["BRAVO","Applauso al cantante"],["BRINA","Gelo bianco del mattino"],
  ["BRODO","Caldo, col dado"],["BRUNO","Castano scuro"],["BUFFO","Fa ridere"],
  ["BURRO","Si spalma sul pane"],["CACAO","Da cui nasce il cioccolato"],["CALMO","Tranquillo e sereno"],
  ["CALVO","Senza capelli"],["CAMPO","Dove gioca la squadra"],["CANTO","Melodia con la voce"],
  ["CARNE","La mangia il carnivoro"],["CARRO","Lo tira il bue"],["CARTA","Su cui si scrive"],
  ["CASCO","Protegge la testa del motociclista"],["CAUSA","Il motivo, la ragione"],["CAVIA","Roditore da laboratorio"],
  ["CELLA","Stanzetta del carcere"],["CERTO","Sicuro, indubbio"],["CESTO","Contenitore di vimini"],
  ["CHINA","Pendio, discesa"],["CICCA","Mozzicone di sigaretta"],["CIECO","Privo della vista"],
  ["CIFRA","Una delle dieci da 0 a 9"],["CINTA","Le mura della citta"],["CIRCO","Quello con i pagliacci"],
  ["CIUCO","L'asino, familiarmente"],["CLIMA","Il tempo di una regione"],["COBRA","Serpente col cappuccio"],
  ["COLLE","Piccola altura"],["COLLO","Unisce testa e tronco"],["COLMO","Pieno fino all'orlo"],
  ["COLPO","Botta improvvisa"],["CONTE","Titolo nobiliare"],["CONTO","Da pagare al ristorante"],
  ["CORDA","Per legare o saltare"],["CORNO","Quello del toro"],["CORPO","Il fisico umano"],
  ["CORSA","Gara di velocita"],["CORSO","Lezione o viale principale"],["CORTE","Quella del re"],
  ["COSTA","Il litorale marino"],["COSTO","Il prezzo da pagare"],["CRUDO","Non cotto"],
  ["CUNEO","Citta del Piemonte"],["CUOCO","Comanda in cucina"],["CUORE","Pompa il sangue"],
  ["CURVA","Non e dritta"],["DANNO","Guasto, perdita"],["DANZA","Il ballo, elegante"],
  ["DARDO","Freccia sottile"],["DELTA","La foce a ventaglio del Po"],["DENTE","Si lava con lo spazzolino"],
  ["DISCO","Il vinile della musica"],["DITTA","Azienda commerciale"],["DOGMA","Verita indiscutibile"],
  ["DOLCE","Il fine pasto zuccherato"],["DONNA","Femmina adulta"],["DUOMO","La cattedrale della citta"],
  ["EBANO","Legno nero pregiato"],["ELICA","Gira sull'aereo a pistoni"],["EPOCA","Lungo periodo storico"]
);

// ===================== 5 LETTERE (parte 2) =====================
NEW.push(
  ["ESAME","Prova da superare a scuola"],["ESILE","Sottile e gracile"],["ESITO","Il risultato finale"],
  ["ESTRO","Ispirazione creativa"],["ETICA","La morale"],["FALCO","Rapace dalla vista acuta"],
  ["FALDA","Strato d'acqua sotterraneo"],["FALSO","Non autentico"],["FANGO","Terra e acqua mescolate"],
  ["FARSA","Commedia buffa"],["FAUNA","Gli animali di un luogo"],["FELCE","Pianta del sottobosco"],
  ["FERMO","Immobile, che non si muove"],["FESTA","Ricorrenza allegra"],["FETTA","Porzione di torta"],
  ["FIABA","Storia per bambini"],["FIATO","Il respiro"],["FIBRA","Filamento del tessuto"],
  ["FIENO","Foraggio secco per i cavalli"],["FIERA","Esposizione commerciale"],["FINTO","Falso, simulato"],
  ["FIORE","Sboccia in primavera"],["FIRMA","Si mette in fondo al documento"],["FIUME","Scorre verso il mare"],
  ["FLORA","Le piante di un luogo"],["FOLLA","Gran quantita di gente"],["FOLLE","Pazzo, insensato"],
  ["FONDO","La parte piu bassa"],["FONTE","Sorgente d'acqua"],["FORCA","Attrezzo a denti del contadino"],
  ["FORMA","La sagoma di un oggetto"],["FORNO","Cuoce il pane"],["FORTE","Robusto e vigoroso"],
  ["FORZA","La potenza fisica"],["FOSSA","Buca profonda"],["FRANA","Smottamento di terreno"],
  ["FRATE","Religioso col saio"],["FRENO","Ferma l'automobile"],["FRODE","Inganno, truffa"],
  ["FUOCO","Brucia e scalda"],["FURBO","Astuto e scaltro"],["FURIA","Rabbia violenta"],
  ["FUSTO","Il tronco della pianta"],["GAMBA","L'arto per camminare"],["GARBO","Gentilezza nei modi"],
  ["GELSO","Albero del baco da seta"],["GEMMA","Pietra preziosa"],["GENIO","Mente geniale"],
  ["GESSO","Per scrivere alla lavagna"],["GESTO","Movimento della mano"],["GIADA","Pietra verde orientale"],
  ["GIOCO","Passatempo divertente"],["GIOIA","Grande felicita"],["GLOBO","Il mappamondo"],
  ["GNOMO","Folletto del bosco"],["GOMMA","Cancella la matita"],["GONNA","Capo femminile"],
  ["GRADO","Unita di temperatura"],["GRANO","Cereale del pane"],["GRECO","Di Atene"],
  ["GRIDO","Urlo improvviso"],["GUADO","Punto per attraversare il fiume"],["GUSTO","Il sapore percepito"],
  ["IDOLO","Beniamino adorato"],["IGLOO","Casa di ghiaccio degli eschimesi"],["IMENE","Il dio greco delle nozze"],
  ["INDIA","Patria del curry"],["IODIO","Disinfettante per ferite"],["IRIDE","Parte colorata dell'occhio"],
  ["ISOLA","Terra circondata dal mare"],["JOLLY","La carta che vale tutto"],["LAGNA","Lamento noioso"],
  ["LARDO","Grasso del maiale"],["LARGO","Ampio, spazioso"],["LARVA","Lo stadio del bruco"],
  ["LASER","Raggio di luce concentrato"],["LATTE","Lo da la mucca"],["LAUTO","Abbondante, ricco"],
  ["LEGGE","La norma da rispettare"],["LEGNO","Materiale dell'albero"],["LEONE","Il re della savana"],
  ["LESTO","Veloce e svelto"],["LIBRO","Si legge pagina dopo pagina"],["LIETO","Contento, felice"],
  ["LINEA","Tratto sottile e dritto"],["LISCA","La spina del pesce"],["LIUTO","Strumento a corde antico"],
  ["LOTTA","Combattimento corpo a corpo"],["LUNGO","Esteso nello spazio"],["LUSSO","Sfarzo e ricchezza"],
  ["LUTTO","Dolore per un defunto"],["MADRE","La mamma"],["MAGIA","Incantesimo"],
  ["MAGMA","Roccia fusa del vulcano"],["MAGRO","Senza grasso"],["MAMMA","La madre, affettuosamente"],
  ["MANGO","Frutto tropicale dolce"],["MANIA","Fissazione ossessiva"],["MANTO","Mantello che copre"],
  ["MARCA","La griffe del prodotto"],["MARMO","Pietra di Carrara"],["MARZO","Il mese di primavera"],
  ["MASSA","Grande quantita"],["MATTO","Pazzo, folle"],["MAZZA","Bastone da baseball"],
  ["MENSA","Si pranza in comune"],["MERLO","Uccello nero dal becco giallo"],["MESTO","Triste e malinconico"],
  ["METRO","Unita di lunghezza"],["MIELE","Dolce dono delle api"],["MIRTO","Liquore sardo"],
  ["MISTO","Mescolato"],["MOLLA","Si comprime e scatta"],["MOLTO","In gran quantita"],
  ["MONDO","Il pianeta Terra"],["MONTE","Grande rilievo"],["MORSO","Boccone dei denti"],
  ["MORTE","La fine della vita"],["MOSCA","Insetto fastidioso"],["MOSSA","Una mossa degli scacchi"]
);

// ===================== 5 LETTERE (parte 3) =====================
NEW.push(
  ["MOSTO","Succo d'uva da vinificare"],["MOTTO","Frase celebre"],["MUCCA","Da il latte"],
  ["MUFFA","Verde sul formaggio dimenticato"],["MULTA","Sanzione per il divieto"],["MUSEO","Custodisce le opere d'arte"],
  ["NANNA","Il sonno dei bimbi"],["NAPPA","Pelle morbida e pregiata"],["NERBO","Vigore, energia"],
  ["NINFA","Spirito femminile dei boschi"],["NONNA","La mamma del genitore"],["NONNO","Il papa del genitore"],
  ["NOTTE","Buia, dopo la sera"],["NUORA","La moglie del figlio"],["NUOTO","Sport in piscina"],
  ["NUOVO","Appena fatto"],["OBESO","Molto in sovrappeso"],["OMERO","Osso del braccio / poeta greco"],
  ["ONERE","Peso, gravame"],["OPALE","Pietra dai riflessi cangianti"],["OPACO","Non trasparente"],
  ["OPERA","Capolavoro lirico"],["ORATA","Pesce pregiato del Mediterraneo"],["OSCAR","Statuetta del cinema"],
  ["OSSEO","Relativo alle ossa"],["OSTIA","Citta della Lombardia? no, lido di Roma"],["OVEST","Dove tramonta il sole"],
  ["OVILE","Il ricovero delle pecore"],["OZONO","Strato che ci protegge dai raggi UV"],["PALCO","Il palcoscenico"],
  ["PALMA","Albero dei datteri"],["PALMO","La mano aperta"],["PALLA","Rotola e rimbalza"],
  ["PANDA","Orso bianco e nero"],["PANNA","Quella montata sul dolce"],["PANNO","Pezzo di stoffa"],
  ["PARCO","Verde pubblico in citta"],["PASSO","Andatura del cammino"],["PASTA","Spaghetti e maccheroni"],
  ["PAUSA","Breve interruzione"],["PELLE","Riveste il corpo"],["PENNA","Scrive a inchiostro"],
  ["PERLA","Nasce nell'ostrica"],["PESCA","Frutto vellutato estivo"],["PESCE","Nuota con le pinne"],
  ["PESTE","Antica epidemia"],["PETTO","Il torace"],["PEZZO","Frammento, parte"],
  ["PIANO","Lo strumento a tasti"],["PIEDE","Termina con le dita"],["PIENO","Colmo, riempito"],
  ["PINNA","Permette al pesce di nuotare"],["PINZA","Attrezzo per stringere"],["PIOLO","Gradino della scala a mano"],
  ["PISTA","Quella da ballo o da sci"],["PIZZA","Margherita o capricciosa"],["PLEBE","Il popolo minuto"],
  ["POEMA","Lunga composizione poetica"],["POETA","Compone versi"],["POLLO","Il galletto da arrosto"],
  ["POLPA","La parte morbida del frutto"],["POLSO","Si tasta per il battito"],["POMPA","Spinge l'acqua"],
  ["PONTE","Unisce le due rive"],["PORCO","Il maiale"],["PORTA","Si apre e si chiude"],
  ["PORTO","Approdo delle navi"],["POSTA","Recapita le lettere"],["POSTO","Sedia o luogo"],
  ["POZZO","Da cui si attinge acqua"],["PRATO","Distesa d'erba"],["PREDA","La caccia il predatore"],
  ["PRESA","Vi si infila la spina"],["PREGO","Risposta a grazie"],["PRETE","Celebra la messa"],
  ["PRIMO","Il numero uno"],["PRODE","Valoroso in battaglia"],["PROSA","Scrittura non in versi"],
  ["PROVA","Tentativo, esperimento"],["PUGNO","Colpo della mano chiusa"],["PULCE","Insetto che salta"],
  ["PUNTA","L'estremita aguzza"],["PUNTO","Segno alla fine della frase"],["PUZZA","Cattivo odore"],
  ["QUOTA","Altitudine / parte dovuta"],["RADAR","Rileva aerei e navi"],["RADIO","Trasmette musica e notizie"],
  ["RAGNO","Tesse la tela"],["RAMPA","Salita ripida"],["RAZZA","Specie di animale"],
  ["RAZZO","Va nello spazio"],["REALE","Del re / autentico"],["REGNO","Il dominio del sovrano"],
  ["RESTO","Cio che avanza"],["RETTA","Linea senza curve"],["RISMA","Pacco di fogli"],
  ["ROBOT","Macchina automatica"],["ROCCA","Fortezza in cima al colle"],["RODEO","Spettacolo dei cowboy"],
  ["ROSEO","Color rosa tenue"],["ROSSO","Il colore del sangue"],["ROTTA","La via della nave"],
  ["RUOLO","La parte dell'attore"],["RUOTA","Gira sull'asse"],["SACCO","Contiene la patate"],
  ["SAGRA","Festa di paese col cibo"],["SALDO","Lo sconto dei negozi"],["SALSA","Condimento denso"],
  ["SALTO","Balzo verso l'alto"],["SANTO","Venerato in paradiso"],["SARTO","Confeziona abiti su misura"],
  ["SASSO","Piccola pietra"],["SAUNA","Bagno di calore secco"],["SCALA","Per salire ai piani"],
  ["SCENA","Parte di un atto teatrale"],["SCOPA","Spazza il pavimento / gioco di carte"],["SCOPO","Il fine, l'obiettivo"],
  ["SCUDO","Difende il guerriero"],["SECCO","Privo di umidita"],["SEDIA","Ci si siede"],
  ["SEGNO","Marchio, traccia"],["SELVA","Bosco fitto e selvaggio"],["SENSO","Vista, udito, tatto..."],
  ["SERPE","Il serpente, poeticamente"],["SERVO","Domestico al servizio"],["SETTE","Numero fortunato"],
  ["SFERA","Solido perfettamente rotondo"],["SFIDA","Provocazione a competere"],["SIEPE","Cespuglio di confine"],
  ["SIGLA","Insieme di iniziali"],["SOGNO","Si fa dormendo"],["SOLCO","La traccia dell'aratro"],
  ["SOLDO","Spicciolo, moneta"],["SONNO","Voglia di dormire"],["SORTE","Il destino, la fortuna"],
  ["SOSTA","Breve fermata"],["SPADA","Arma da scherma"],["SPESA","Acquisti al supermercato"],
  ["SPIGA","Quella del grano"],["SPINA","Punge sulla rosa"],["SPORT","Attivita fisica agonistica"],
  ["SPOSA","La donna il giorno delle nozze"],["STILE","Modo personale e elegante"],["STOLA","Sciarpa elegante"],
  ["STUFA","Riscalda la stanza"],["SUONO","Lo percepisce l'orecchio"],["SUORA","Religiosa col velo"],
  ["SVAGO","Passatempo rilassante"],["TACCO","Quello a spillo della scarpa"],["TANGO","Ballo argentino"],
  ["TARGA","Identifica l'auto"],["TARLO","Rode il legno / dubbio fisso"],["TASCA","Cucita nei pantaloni"],
  ["TASTO","Quello del pianoforte"],["TEMPO","Passa inesorabile"],["TENDA","Riparo del campeggio"],
  ["TERRA","Il nostro pianeta"],["TERZO","Dopo il secondo"],["TESTA","Il capo"],
  ["TIGRE","Felino a strisce"],["TINTA","Colore, tinteggiatura"],["TOMBA","Custodisce il defunto"],
  ["TONDO","Rotondo"],["TONNO","Pesce in scatola"],["TORTA","Si taglia a fette al compleanno"],
  ["TORTO","Il contrario della ragione"],["TORRE","Quella di Pisa pende"],["TOSSE","Sintomo del raffreddore"],
  ["TRAVE","Sostiene il tetto"],["TRENO","Viaggia sui binari"],["TRIBU","Comunita di un capo"],
  ["TRONO","Il seggio del re"],["TROTA","Pesce di torrente"],["TUONO","Segue il lampo"],
  ["TURNO","Si fa a rotazione"],["UDITO","Il senso dell'orecchio"],["UGOLA","Pende in fondo alla gola"],
  ["UMORE","Lo stato d'animo"],["VALLE","Tra due montagne"],
  ["VARCO","Passaggio, apertura"],["VENTO","Aria in movimento"],["VERBO","La parola che indica azione"],
  ["VERDE","Il colore dell'erba"],["VERME","Striscia nella terra"],["VERSO","Riga di una poesia"],
  ["VESPA","Insetto con il pungiglione"],["VESTE","L'abito"],["VETRO","Trasparente e fragile"],
  ["VIALE","Strada alberata"],["VIDEO","Filmato da guardare"],["VIGNA","Filari di viti"],
  ["VILLA","Casa signorile col giardino"],["VIOLA","Colore tra blu e rosso"],["VIRUS","Causa l'influenza"],
  ["VISTA","Il senso degli occhi"],["VIZIO","Cattiva abitudine"],["VOLTO","Il viso, il volto"],
  ["ZAINO","Si porta sulle spalle"],["ZAMPA","La gamba dell'animale"],["ZANNA","Il dente dell'elefante"],
  ["ZAPPA","Lavora la terra dell'orto"],["ZEBRA","Equino a strisce"],["ZUPPA","Minestra densa"]
);

// ===================== 6 LETTERE =====================
NEW.push(
  ["AMBITO","Campo, settore"],["ANCORA","Tiene ferma la nave"],["ANELLO","Si porta al dito"],
  ["ANGELO","Creatura celeste con le ali"],["ANGINA","Infiammazione della gola"],["ANGOLO","Lo formano due lati"],
  ["AQUILA","Rapace simbolo di Roma"],["ARDORE","Passione ardente"],["ARGINE","Trattiene il fiume"],
  ["ARNESE","Attrezzo da lavoro"],["AVORIO","La zanna dell'elefante"],["AZALEA","Pianta dai fiori rosa"],
  ["AZIONE","Quota di una societa"],["BACINO","Insenatura o anca"],["BALENA","Il piu grande dei mammiferi"],
  ["BANANA","Frutto giallo allungato"],["BARILE","Contiene il petrolio"],["BRONZO","Lega di rame e stagno"],
  ["BUFALO","Da la mozzarella"],["CACCIA","Va a prede"],["CALCIO","Sport con il pallone"],
  ["CAMINO","Il focolare di casa"],["CANALE","Corso d'acqua artificiale"],["CAROTA","Ortaggio arancione"],
  ["CENERE","Resta dopo il fuoco"],["CHIAVE","Apre la serratura"],["CHIESA","Edificio di culto"],
  ["CINEMA","Si proiettano i film"],["CIUFFO","Ciocca di capelli"],["CODICE","Insieme di regole"],
  ["COLORE","Rosso, blu o giallo"],["COMETA","Astro con la coda"],["COMODO","Confortevole"],
  ["CORONA","Cinge il capo del re"],["COTONE","Fibra naturale per magliette"],["CUCINA","Vi si preparano i pasti"],
  ["DIESEL","Carburante del camion"],["DOMINO","Gioco con le tessere"],["EFFIGE","Immagine, ritratto"],
  ["ENZIMA","Catalizzatore biologico"],["ERRORE","Sbaglio, svista"],["ESTATE","La stagione calda"],
  ["FABBRO","Lavora il ferro"],["FAGGIO","Albero dei boschi montani"],["FANALE","Faro dell'auto"],
  ["FARINA","Si macina dal grano"],["FATICA","Sforzo intenso"],["FAVOLA","Racconto con la morale"],
  ["FEBBRE","Temperatura alta del corpo"],["FENICE","Risorge dalle sue ceneri"],["FERITA","Taglio sulla pelle"],
  ["FIBBIA","Chiude la cintura"],["FIGURA","Forma, sagoma"],["FINALE","L'ultima partita"],
  ["FORMICA","Insetto operoso"],["GABBIA","Rinchiude l'uccellino"],["GALERA","La prigione"],
  ["GELATO","Dolce freddo estivo"],["GENERE","Tipo, categoria"],["GHETTO","Quartiere segregato"],
  ["GIACCA","Capo sopra la camicia"],["GIRINO","La larva della rana"],["GIUGNO","Il mese dell'estate"],
  ["GOMITO","Piega il braccio"],["GRAPPA","Distillato di vinacce"],["GROTTA","Cavita naturale"],
  ["GRUPPO","Insieme di persone"],["GUANTO","Copre la mano"],["IGUANA","Grosso rettile tropicale"],
  ["INDACO","Blu intenso"],["INERTE","Immobile, inattivo"],["LAGUNA","Quella di Venezia"],
  ["LEGAME","Vincolo, rapporto"],["LIMONE","Agrume giallo e aspro"],["LINGUA","Idioma o organo del gusto"],
  ["LUMACA","Lascia la bava lenta"],["MAGLIA","Indumento di lana"],["MANICA","Avvolge il braccio"],
  ["MANTRA","Formula da ripetere"],["MELONE","Frutto estivo dolce"],["METODO","Modo ordinato di fare"],
  ["MIMOSA","Fiore giallo dell'8 marzo"],["MISURA","Si prende col metro"],["MOBILE","Tavolo o armadio"],
  ["MONACO","Vive in convento"],["MORALE","L'insegnamento della favola"],["MOTORE","Muove l'automobile"],
  ["MULINO","Macina il grano"],["NEMICO","L'avversario"],["NIENTE","Nulla del tutto"],
  ["NIPOTE","Il figlio del figlio"],["NUVOLA","Porta la pioggia"],["OFFESA","Insulto, ingiuria"],
  ["OSCURO","Buio, tenebroso"],["OTTONE","Lega di rame e zinco"],["PALUDE","Terreno acquitrinoso"],
  ["PANINO","Imbottito col prosciutto"],["PARETE","Il muro della stanza"],["PAROLA","Insieme di lettere"],
  ["PATATA","Tubero da friggere"],["PAVONE","Fa la ruota colorata"],["PEDALE","Si spinge in bici"],
  ["PEPITA","Pezzo d'oro grezzo"],["PETALO","Parte colorata del fiore"],["PIANTA","Vegetale con radici"],
  ["PIATTO","Vi si mette il cibo"],["PIAZZA","Spazio aperto in citta"],["PILOTA","Guida l'aereo"],
  ["PINOLO","Seme della pigna"],["PIRATA","Bucaniere dei mari"],["PITONE","Grosso serpente costrittore"],
  ["POMATA","Crema medicinale"],["POTERE","Autorita, facolta"],["PRANZO","Il pasto di mezzogiorno"],
  ["PUGILE","Tira pugni sul ring"],["QUADRO","Dipinto appeso al muro"],["QUIETE","Calma e tranquillita"],
  ["RABBIA","Collera furiosa"],["RAPACE","Uccello predatore"],["REGOLA","Norma da seguire"],
  ["RICAMO","Decorazione cucita"],["RICCIO","Punge col suo manto / di mare"],["RIPOSO","Pausa per riprendersi"],
  ["RISATA","Scoppio di ilarita"],["RIVALE","L'avversario in gara"],["ROCCIA","Masso di pietra dura"],
  ["ROVERE","Robusta quercia"],["ROVINA","Crollo, disastro"],["RUMORE","Suono fastidioso"],
  ["SALAME","Insaccato a fette"],["SALICE","Albero piangente"],["SALONE","Grande sala"],
  ["SALUTO","Ciao o arrivederci"],["SAPONE","Per lavarsi le mani"],["SAPORE","Dolce, salato, amaro"],
  ["SCHEDA","Cartoncino con dati"],["SEDANO","Ortaggio a coste verdi"],["SESAMO","Apriti...!"],
  ["SFINGE","Mostro con corpo di leone"],["SILURO","Arma subacquea"],["SIRENA","Donna-pesce ammaliatrice"],
  ["SOGLIA","L'ingresso della porta"],["SPALLA","Sostiene il braccio"],["SPECIE","Categoria di esseri viventi"],
  ["SQUALO","Predatore del mare"],["STAGNO","Piccolo lago fermo"],["STALLA","Ricovero delle mucche"],
  ["STANZA","Vano della casa"],["STELLA","Brilla nel cielo notturno"],["STORIA","Racconto del passato"],
  ["STRADA","La percorrono le auto"],["STREGA","Vola sulla scopa"],["SUDORE","Esce con la fatica"],
  ["TEMPIO","Luogo sacro antico"],["TENORE","Voce maschile acuta"],["TEORIA","Insieme di ipotesi"],
  ["TESORO","Forziere di ricchezze"],["TIMORE","Paura, apprensione"],["TONACA","La veste del frate"],
  ["TORACE","Il petto"],["TORERO","Affronta il toro"],["TORNEO","Competizione a eliminazione"],
  ["TROFEO","La coppa del vincitore"],["TROPPO","Piu del necessario"],["TRUFFA","Raggiro, inganno"],
  ["TUMORE","Massa di cellule malata"],["TUNICA","Veste lunga e ampia"],["TUTORE","Sostiene la pianta / il minore"],
  ["UNIONE","Insieme, alleanza"],["VAGONE","Carrozza del treno"],["VALORE","Quanto vale qualcosa"],
  ["VAPORE","Acqua che bolle"],["VEDOVA","Ha perso il marito"],["VELENO","Sostanza letale"],
  ["VELOCE","Rapido, svelto"],["VENERE","La dea della bellezza"],["VERMUT","Vino aromatizzato da aperitivo"],
  ["VICINO","Non lontano / il dirimpettaio"],["VIGILE","Dirige il traffico"],["VIGORE","Forza ed energia"],
  ["VIMINI","Per le sedie intrecciate"],["ZEFIRO","Vento leggero di ponente"]
);

// ===================== 7 LETTERE =====================
NEW.push(
  ["ALBERGO","Ci si pernotta in viaggio"],["ALLEGRO","Di buon umore"],["ARANCIO","Albero degli agrumi"],
  ["ARMADIO","Custodisce i vestiti"],["ATLANTE","Raccolta di carte geografiche"],["AUTUNNO","Cadono le foglie"],
  ["BACHECA","Vi si appendono gli avvisi"],["BALCONE","Sporge dalla facciata"],["BAMBINO","Piccolo di eta"],
  ["BARBONE","Cane riccioluto / senzatetto"],["BARCONE","Grossa imbarcazione"],["BATTITO","Il pulsare del cuore"],
  ["BOTTEGA","Piccolo negozio artigiano"],["BOTTONE","Si cuce sulla camicia"],["BRACCIO","Arto superiore"],
  ["BRINDISI","Si fa coi calici"],["BUSSOLA","Indica il nord"],["CANTINA","Si conserva il vino"],
  ["CAPANNA","Rifugio rustico"],["CARDINE","Su cui gira la porta"],["CARTONE","La scatola di imballo"],
  ["CASCATA","Salto d'acqua"],["CAVALLO","Galoppa nella prateria"],["CAVERNA","Grotta profonda"],
  ["CAVIALE","Uova di storione pregiate"],["CEMENTO","Lega i mattoni"],["CHIMERA","Sogno irrealizzabile"],
  ["CICOGNA","Porta i bambini, si dice"],["CINGHIA","Cintura di cuoio"],["CIPOLLA","Fa lacrimare in cucina"],
  ["CLARINO","Strumento a fiato di legno"],["COLLINA","Rilievo dolce"],["COLOMBA","Simbolo della pace"],
  ["COLONNA","Sostiene il tempio greco"],["CORALLO","Rosso, cresce nei mari caldi"],["CORTILE","Spazio interno del palazzo"],
  ["COSTUME","Si indossa al mare"],["CRATERE","La bocca del vulcano"],["CUSCINO","Sotto la testa nel letto"],
  ["DELFINO","Mammifero marino intelligente"],["DESERTO","Distesa di sabbia arida"],["DIADEMA","Corona preziosa femminile"],
  ["DIPLOMA","Si ottiene a fine scuola"],["DRAGONE","Mostro sputafuoco"],["FAGIANO","Uccello dal piumaggio vistoso"],
  ["FANTINO","Cavalca nel palio"],["FERMATA","Dove sale l'autobus"],["FORBICE","Taglia la carta"],
  ["FORTINO","Piccola fortezza"],["FOSSILE","Resto pietrificato antico"],["FRAGOLA","Frutto rosso primaverile"],
  ["FRECCIA","Scoccata dall'arco"],["FUMETTO","Storia a nuvolette"],["GALLINA","Depone le uova"],
  ["GALOPPO","Corsa veloce del cavallo"],["GAMBERO","Cammina all'indietro"],["GEMELLO","Nato nello stesso parto"],
  ["GENTILE","Cortese e garbato"],["GERANIO","Fiore da balcone"],["GIUNGLA","Foresta tropicale fitta"],
  ["GONDOLA","La barca di Venezia"],["GORILLA","La scimmia piu grande"],["GRAFITE","La mina della matita"],
  ["INSEGNA","Cartello del negozio"],["INVERNO","La stagione fredda"],["ISTANTE","Un attimo brevissimo"],
  ["ISTRICE","Roditore con gli aculei"],["LAMPADA","Fa luce sulla scrivania"],["LAMPONE","Frutto rosso del bosco"],
  ["LASAGNA","Pasta al forno a strati"],["LAVAGNA","Si scrive col gesso"],["LIBRAIO","Vende libri"],
  ["LIQUORE","Bevanda alcolica dolce"],["MACELLO","Vi si abbattono le bestie"],["MARGINE","Bordo del foglio"],
  ["MATTONE","Si usa per murare"],["METEORA","Stella cadente"],["MIDOLLO","Dentro le ossa"],
  ["MIGNOLO","Il dito piu piccolo"],["MONTONE","Il maschio della pecora"],["MUSCOLO","Si contrae e muove l'osso"],
  ["NETTARE","Bevanda degli dei"],["OCARINA","Piccolo strumento a fiato"],["OFFERTA","Proposta vantaggiosa"],
  ["ORACOLO","Predice il futuro"],["ORIGANO","Aroma della pizza"],["PADELLA","Per friggere"],
  ["PADRONE","Il proprietario"],["PALAZZO","Grande edificio"],["PASSERO","Uccellino di citta"],
  ["PASTORE","Custodisce il gregge"],["PENTOLA","Bolle sul fuoco"],["PIANETA","Orbita intorno al sole"],
  ["PICCONE","Attrezzo del minatore"],["PISELLO","Legume verde nel baccello"],["PISTOLA","Arma da fuoco corta"],
  ["POLLAIO","La casa delle galline"],["PORTONE","Il grande portale d'ingresso"],["PRESEPE","Natale: grotta e pastori"],
  ["PRIMULA","Fiorellino di inizio primavera"],["PROFUMO","Fragranza gradevole"],["PULCINO","Il piccolo della gallina"],
  ["QUERCIA","Albero della ghianda"],["RICETTA","Le istruzioni del piatto"],["RIMEDIO","La cura del male"],
  ["RONDINE","Torna a primavera"],["ROSARIO","Si recita con i grani"],["SARDINA","Pesciolino in scatola"],
  ["SCATOLA","Contenitore di cartone"],["SCHIENA","La parte dorsale"],["SCOPPIO","Esplosione fragorosa"],
  ["SIGNORE","Uomo distinto"],["SIMBOLO","Segno che rappresenta"],["SIPARIO","Si apre sul palco"],
  ["SOLDATO","Veste la divisa militare"],["SORELLA","La figlia degli stessi genitori"],["SORRISO","Espressione lieta"],
  ["SPINACI","Verdura di Braccio di Ferro"],["SPIRITO","L'anima / il fantasma"],["TACCHINO","Si mangia a Natale"],
  ["TALENTO","Dote naturale"],["TAMBURO","Si suona con le bacchette"],["TAPPETO","Copre il pavimento"],
  ["TARTUFO","Fungo pregiato sotterraneo"],["TERMINE","La fine, la scadenza"],["TERRORE","Paura estrema"],
  ["TIRANNO","Despota crudele"],["TORNADO","Tromba d'aria devastante"],["TRAPANO","Fa i buchi nel muro"],
  ["UCCELLO","Vola con le ali e il becco"],["UFFICIO","Vi si lavora alla scrivania"],["VESCOVO","Guida la diocesi"],
  ["VETRINA","Espone la merce del negozio"],["VIAGGIO","Spostamento lontano"],["VIOLINO","Si suona con l'archetto"],
  ["VULCANO","Erutta lava"],["ZAFFIRO","Pietra preziosa blu"],["ZENZERO","Radice piccante orientale"],
  ["ZOCCOLO","Calzatura di legno"]
);

// ===================== 8 LETTERE =====================
NEW.push(
  ["ACQUARIO","Vasca per i pesci"],["ALLODOLA","Uccello canterino dei campi"],["ALTALENA","Va su e giu al parco"],
  ["AMBIENTE","Cio che ci circonda"],["ANTILOPE","Erbivoro veloce africano"],["ARMATURA","Difesa del cavaliere"],
  ["ASPARAGO","Ortaggio a turione"],["ASTUCCIO","Custodisce le penne"],["BAGAGLIO","La valigia del viaggio"],
  ["BANDIERA","Sventola sul pennone"],["BASILICO","Aroma del pesto"],["BISCOTTO","Si inzuppa nel latte"],
  ["CALAMARO","Mollusco coi tentacoli"],["CALAMITA","Attira il ferro"],["CAMOSCIO","Capra delle Alpi"],
  ["CAMPIONE","Il vincitore assoluto"],["CANTANTE","Interpreta canzoni"],["CANTIERE","Dove si costruisce"],
  ["CARABINA","Fucile da caccia"],["CAROVANA","Fila di carri nel deserto"],["CARRELLO","Spinge la spesa"],
  ["CASTELLO","Maniero medievale"],["CENTAURO","Mezzo uomo e mezzo cavallo"],["CERVELLO","Sede del pensiero"],
  ["CETRIOLO","Ortaggio verde da insalata"],["COCOMERO","L'anguria"],["COLOSSEO","Anfiteatro di Roma"],
  ["CONIGLIO","Roditore dalle lunghe orecchie"],["CONTESSA","Moglie del conte"],["CORNETTA","La parte del telefono"],
  ["CRISTALLO","Vetro pregiato"],["CROSTATA","Torta con la marmellata"],["CUCCIOLO","Il piccolo del cane"],
  ["DENTISTA","Cura i denti"],["DIAMANTE","La piu dura delle pietre"],["ELEFANTE","Pachiderma con la proboscide"],
  ["ESERCITO","Le forze armate di terra"],["FANTASMA","Spettro che appare di notte"],["FARFALLA","Vola coi colori sulle ali"],
  ["FELICITA","Stato di gioia piena"],["FINESTRA","Si apre per arieggiare"],["FRATELLO","Il figlio maschio dei genitori"],
  ["FRONTONE","Timpano del tempio"],["GABBIANO","Volteggia sul porto"],["GALASSIA","Insieme di miliardi di stelle"],
  ["GIARDINO","Vi crescono i fiori"],["GIORNALE","Si legge ogni mattina"],["GIRASOLE","Segue il sole nel campo"],
  ["GRANDINE","Chicchi di ghiaccio dal cielo"],["GRANELLO","Minuscolo frammento"],["INCUDINE","Su cui batte il fabbro"],
  ["LAMPIONE","Illumina la strada"],["LEOPARDO","Felino maculato"],["MACCHINA","L'automobile"],
  ["MANTELLO","Mantella che copre le spalle"],["MARTELLO","Pianta i chiodi"],["MERLUZZO","Pesce dal quale l'olio"],
  ["MINESTRA","Brodo con verdure"],["MONTAGNA","Alto rilievo roccioso"],["MUGHETTO","Fiorellini bianchi a campanella"],
  ["NOCCIOLO","L'albero della nocciola"],["OFFICINA","Si riparano le auto"],["OMBRELLO","Ripara dalla pioggia"],
  ["ORCHIDEA","Fiore elegante ed esotico"],["OSPEDALE","Vi si curano i malati"],["PANCETTA","Insaccato per la carbonara"],
  ["PANCHINA","Per sedersi al parco"],["PIANISTA","Suona il pianoforte"],["PINGUINO","Uccello che non vola, dei poli"],
  ["PIRAMIDE","Tomba dei faraoni"],["POLTRONA","Comoda con i braccioli"],["PRESEPIO","Natività natalizia"],
  ["QUADERNO","Per gli appunti di scuola"],["RISOTTO","Piatto di riso mantecato"],["SALOTTO","Stanza con il divano"],
  ["SCARABEO","Coleottero sacro agli egizi"],["SCARPONE","Calzatura da montagna"],["SCIROPPO","Medicina dolce e liquida"],
  ["SCULTURA","Statua dell'artista"],["SEGGIOLA","La sedia, familiarmente"],["SENTIERO","Stretto cammino di montagna"],
  ["SERPENTE","Striscia senza zampe"],["SOFFITTO","La parte alta della stanza"],["SORGENTE","Da cui sgorga l'acqua"],
  ["SPAVENTO","Paura improvvisa"],["SPIAGGIA","Sabbia in riva al mare"],["TASTIERA","Si digita al computer"],
  ["TELEFONO","Si compone il numero"],["TEMPESTA","Burrasca violenta"],["TERRAZZA","Ampio balcone panoramico"],
  ["TRAMONTO","Il sole cala all'orizzonte"],["TRAPEZIO","Quadrilatero / attrezzo del circo"],["TRATTORE","Lavora nei campi"],
  ["TROMBONE","Ottone con la coulisse"],["USIGNOLO","Canta melodioso di notte"],["ZUCCHINA","Ortaggio verde allungato"]
);

// ===================== 9+ LETTERE =====================
NEW.push(
  ["COCCINELLA","Rossa a pois neri, porta fortuna"],["COCCODRILLO","Rettile delle paludi africane"],
  ["ELICOTTERO","Vola con le pale rotanti"],["FENICOTTERO","Trampoliere rosa"],
  ["LIBELLULA","Insetto con quattro ali trasparenti"],["LOCOMOTIVA","Traina i vagoni"],
  ["MANDARINO","Agrume facile da sbucciare"],["ORECCHINO","Pende dal lobo"],
  ["PROVINCIA","Suddivisione della regione"],["RICCHEZZA","Abbondanza di beni"],
  ["SCOIATTOLO","Roditore con la coda folta"],["SCORPIONE","Punge con la coda"],
  ["TARTARUGA","Lenta, con il guscio"],["TRIANGOLO","Poligono a tre lati"],
  ["VENTAGLIO","Fa aria nelle giornate calde"],["BALLERINA","Danza sulle punte"],
  ["AEROPORTO","Decollano gli aerei"],["CAVALIERE","Combatte in armatura"]
);

module.exports = NEW;
